"""Constants for JSON analysis."""

RESOURCE_SKIP_SEGMENTS = {"api", "rest", "graphql", "v1", "v2", "v3", "internal"}
PAGINATION_PARAM_NAMES = {"page", "offset", "limit", "per_page", "page_size"}
FILTER_MUTATIONS = {
    "role": "admin",
    "roles": "admin",
    "status": "all",
    "state": "all",
    "type": "all",
    "view": "full",
    "scope": "global",
    "tenant": "global",
    "include": "all",
    "include_deleted": "true",
    "archived": "true",
    "is_admin": "true",
    "admin": "true",
    "permissions": "admin",
    "permission": "admin",
    "filter": "all",
    "show_all": "true",
    "show_deleted": "true",
    "show_hidden": "true",
    "show_inactive": "true",
    "show_archived": "true",
    "show_private": "true",
    "show_internal": "true",
    "visibility": "all",
    "access_level": "admin",
    "user_role": "admin",
    "account_type": "admin",
    "organization": "all",
    "org_id": "0",
    "team": "all",
    "group": "all",
    "category": "all",
    "level": "all",
    "depth": "all",
    "limit": "999999",
    "max_results": "999999",
    "page_size": "999999",
}
ROLE_MUTATION_PARAM_NAMES = {"role", "roles", "scope", "permission", "permissions", "admin"}
SESSION_PARAM_NAMES = {
    "token",
    "access_token",
    "id_token",
    "refresh_token",
    "session",
    "sessionid",
    "sid",
    "jwt",
    "auth",
}
DEPENDENCY_PARAM_NAMES = {
    "price",
    "quantity",
    "qty",
    "amount",
    "total",
    "currency",
    "discount",
    "coupon",
    "promo",
    "role",
    "roles",
    "permission",
    "permissions",
    "scope",
}
STATE_PARAM_NAMES = {
    "status",
    "state",
    "step",
    "stage",
    "action",
    "confirm",
    "approved",
    "complete",
    "completed",
}
AUTH_REQUIRED_FIELD_HINTS = {
    "email",
    "user_id",
    "account_id",
    "tenant_id",
    "session",
    "token",
    "role",
    "permissions",
}
PUBLIC_AUTH_PAGE_HINTS = {
    "login",
    "signin",
    "sign in",
    "register",
    "forgot password",
    "reset password",
    "create account",
}
WRITE_PATH_HINTS = {
    "/create",
    "/delete",
    "/destroy",
    "/logout",
    "/purchase",
    "/refund",
    "/remove",
    "/reset",
    "/revoke",
    "/session/end",
    "/session/logout",
    "/signout",
    "/update",
    "/write",
}
