"""WAF fingerprint signatures and detection logic."""

from typing import Any

WAF_SIGNATURES: list[dict[str, Any]] = [
    {
        "name": "Cloudflare",
        "status_codes": [403],
        "headers": ["cf-ray", "cf-cache-status", "server"],
        "header_values": {"server": ["cloudflare"]},
        "body_markers": ["cloudflare", "cf-error"],
    },
    {
        "name": "CloudFront (AWS)",
        "status_codes": [403],
        "headers": ["x-amz-cf-id", "x-amz-cf-pop"],
        "header_values": {},
        "body_markers": ["cloudfront", "generated by cloudfront"],
    },
    {
        "name": "AWS WAF",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["aws waf", "aws.waf"],
    },
    {
        "name": "ModSecurity",
        "status_codes": [403, 406],
        "headers": [],
        "header_values": {},
        "body_markers": ["modsecurity", "mod_security", "modsecurity web application firewall"],
    },
    {
        "name": "Imperva/Incapsula",
        "status_codes": [403],
        "headers": ["x-iinfo", "x-cdn"],
        "header_values": {},
        "body_markers": ["incapsula", "imperva", "incap_ses"],
    },
    {
        "name": "F5 BIG-IP ASM",
        "status_codes": [403],
        "headers": ["x-waf-status", "x-waf-request-id"],
        "header_values": {},
        "body_markers": ["big-ip", "f5 networks", "f5 big-ip"],
    },
    {
        "name": "F5 FirePass",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["firepass"],
    },
    {
        "name": "Sucuri WAF",
        "status_codes": [403],
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "header_values": {},
        "body_markers": ["sucuri", "sucuri web site firewall"],
    },
    {
        "name": "Akamai Kona",
        "status_codes": [400, 403],
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "header_values": {},
        "body_markers": ["akamai", "akamai ghost"],
    },
    {
        "name": "FortiWeb",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["fortiweb"],
    },
    {
        "name": "Barracuda WAF",
        "status_codes": [403],
        "headers": ["bar-raider"],
        "header_values": {},
        "body_markers": ["barracuda"],
    },
    {
        "name": "Citrix NetScaler",
        "status_codes": [403],
        "headers": ["ns-cache"],
        "header_values": {},
        "body_markers": ["citrix", "netscaler"],
    },
    {
        "name": "DenyAll WAF",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["denyall", "denied by denyall"],
    },
    {
        "name": "Jiasule WAF",
        "status_codes": [403],
        "headers": ["jiasule-waf", "js_id"],
        "header_values": {},
        "body_markers": ["jiasule", "static.jiasule.com"],
    },
    {
        "name": "NSFocus WAF",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["nsfocus"],
    },
    {
        "name": "Safe3 WAF",
        "status_codes": [403],
        "headers": ["safe3waf", "x-powered-by-safe3"],
        "header_values": {},
        "body_markers": ["safe3"],
    },
    {
        "name": "DotDefender",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["dotdefender", "applicure"],
    },
    {
        "name": "Yundun WAF",
        "status_codes": [403],
        "headers": ["yundun"],
        "header_values": {},
        "body_markers": ["yundun"],
    },
    {
        "name": "Comodo WAF",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["comodo", "cwwaf"],
    },
    {
        "name": "HyperGuard (Art of Defense)",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["hyperguard"],
    },
    {
        "name": "Radware AppWall",
        "status_codes": [403],
        "headers": ["x-sl-compstate"],
        "header_values": {},
        "body_markers": ["radware", "appwall", "unauthorized"],
    },
    {
        "name": "Reblaze WAF",
        "status_codes": [403],
        "headers": [],
        "header_values": {},
        "body_markers": ["reblaze"],
    },
    {
        "name": "Microsoft URLScan",
        "status_codes": [404],
        "headers": [],
        "header_values": {},
        "body_markers": ["urlscan", "rejected-by-urlscan"],
    },
    {
        "name": "NAXSI (Nginx)",
        "status_codes": [403],
        "headers": ["x-data-origin"],
        "header_values": {},
        "body_markers": ["naxsi", "blocked by naxsi"],
    },
]

_COMPILED_WAF_SIGNATURES = [
    {
        "name": sig["name"],
        "status_codes": set(sig["status_codes"]),
        "headers": [h.lower() for h in sig["headers"]],
        "header_values": {k.lower(): [v.lower() for v in vals] for k, vals in sig.get("header_values", {}).items()},
        "body_markers": [m.lower() for m in sig["body_markers"]],
    }
    for sig in WAF_SIGNATURES
]

def _detect_waf(
    status_code: int,
    headers: dict[str, str],
    body: str,
) -> str | None:
    """Check response fingerprints against known WAF signatures.

    Returns the WAF name if detected, or None if no WAF signature matched.
    """
    lower_body = body.lower()
    lower_headers = {k.lower(): v.lower() for k, v in headers.items()}

    for sig in _COMPILED_WAF_SIGNATURES:
        score = 0

        if status_code in sig["status_codes"]:
            score += 1

        for hdr in sig["headers"]:
            if hdr in lower_headers:
                score += 2

        for hdr_key, hdr_vals in sig.get("header_values", {}).items():
            hdr_lower = lower_headers.get(hdr_key, "")
            if any(v in hdr_lower for v in hdr_vals):
                score += 2

        for marker in sig["body_markers"]:
            if marker in lower_body:
                score += 1

        if score >= 2:
            return str(sig["name"])

    return None
