from src.analysis.plugins import analysis_check_options

ANALYSIS_CONTROL_GROUPS = [
    {
        "name": "exposure",
        "label": "Exposure",
        "description": "Surface secrets, headers, caching mistakes, debug artifacts, and general exposure signals.",
        "icon": "👁️",
    },
    {
        "name": "access",
        "label": "Access Control",
        "description": "Compare identity and role contexts, boundary shifts, auth consistency, and privilege changes.",
        "icon": "🔐",
    },
    {
        "name": "idor",
        "label": "IDOR And Object Graph",
        "description": "Learn identifier patterns, compare object references, and walk JSON structures around likely objects.",
        "icon": "🔗",
    },
    {
        "name": "session",
        "label": "Auth And Session",
        "description": "Track token reuse, logout behavior, token scope, and cross-endpoint auth consistency.",
        "icon": "🎫",
    },
    {
        "name": "logic",
        "label": "Business Logic",
        "description": "Probe state shifts, parameter coupling, flow order, and controlled behavior changes.",
        "icon": "🧩",
    },
    {
        "name": "redirect",
        "label": "Redirect And Flow",
        "description": "Inspect redirect chains, auth-boundary transitions, and callback-style behavior.",
        "icon": "↪️",
    },
    {
        "name": "active",
        "label": "Active Probes",
        "description": "Low-risk request mutations and method probes for higher-confidence execution.validators.",
        "icon": "⚡",
    },
]

ANALYSIS_FOCUS_PRESETS = [
    {
        "name": "all",
        "label": "Full Coverage",
        "description": "Keep broad passive coverage with the newer access, session, and logic checks enabled.",
        "checks": "ALL",
    },
    {
        "name": "access",
        "label": "Access Focus",
        "description": "Bias the passive layer toward identity, role, privilege, and IDOR comparisons.",
        "checks": [
            "idor_candidate_finder",
            "response_diff_engine",
            "flow_detector",
            "cross_user_access_simulation",
            "role_based_endpoint_comparison",
            "privilege_escalation_detector",
            "access_boundary_tracker",
            "unauth_access_check",
            "behavior_analysis_layer",
        ],
    },
    {
        "name": "session",
        "label": "Session Focus",
        "description": "Emphasize token propagation, session lifecycle, and multi-endpoint auth consistency.",
        "checks": [
            "token_leak_detector",
            "response_snapshot_system",
            "session_reuse_detection",
            "logout_invalidation_check",
            "multi_endpoint_auth_consistency_check",
            "token_scope_analyzer",
            "referer_propagation_tracking",
            "unauth_access_check",
        ],
    },
    {
        "name": "logic",
        "label": "Logic Focus",
        "description": "Favor state and flow manipulation checks with response-diff and behavior replay support.",
        "checks": [
            "response_diff_engine",
            "parameter_pollution_exploitation",
            "auth_header_tampering_variations",
            "json_mutation_attacks",
            "flow_detector",
            "multi_step_flow_breaking_probe",
            "smart_payload_suggestions",
            "behavior_analysis_layer",
            "state_transition_analyzer",
            "parameter_dependency_tracker",
            "flow_integrity_checker",
            "redirect_chain_analyzer",
            "auth_boundary_redirect_detection",
        ],
    },
    {
        "name": "exposure",
        "label": "Exposure Focus",
        "description": "Bias the run toward exposed interfaces, configs, storage, AI surfaces, and passive hardening signals.",
        "checks": [
            "sensitive_data_scanner",
            "header_checker",
            "cookie_security_checker",
            "cors_misconfig_checker",
            "cache_control_checker",
            "frontend_config_exposure_checker",
            "directory_listing_checker",
            "debug_artifact_checker",
            "graphql_introspection_exposure_checker",
            "graphql_error_leakage_checker",
            "openapi_swagger_spec_checker",
            "ai_endpoint_exposure_analyzer",
            "grpc_reflection_exposure_checker",
            "cloud_storage_exposure_checker",
            "subdomain_takeover_indicator_checker",
            "service_worker_misconfiguration_checker",
            "csp_weakness_analyzer",
            "referrer_policy_weakness_checker",
            "hsts_weakness_checker",
            "dns_misconfiguration_signal_checker",
            "api_version_disclosure_checker",
            "rate_limit_header_analyzer",
            "error_stack_trace_detector",
            "cdn_waf_fingerprint_gap_checker",
            "public_repo_exposure_checker",
            "backup_file_exposure_checker",
            "environment_file_exposure_checker",
            "log_file_exposure_checker",
            "http_method_exposure_checker",
            "third_party_key_exposure_checker",
        ],
    },
    {
        "name": "api_ai",
        "label": "API And AI Focus",
        "description": "Favor JSON, schema, AI inference, and server-side surface analysis for modern API targets.",
        "checks": [
            "json_response_parser",
            "json_schema_inference",
            "sensitive_field_detector",
            "cross_tenant_pii_risk_analyzer",
            "bulk_endpoint_detector",
            "pagination_walker",
            "filter_parameter_fuzzer",
            "error_based_inference",
            "json_mutation_attacks",
            "version_diffing",
            "rate_limit_header_analyzer",
            "rate_limit_signal_analyzer",
            "ai_endpoint_exposure_analyzer",
            "openapi_swagger_spec_checker",
            "graphql_introspection_exposure_checker",
            "graphql_error_leakage_checker",
            "grpc_reflection_exposure_checker",
            "server_side_injection_surface_analyzer",
            "parameter_pollution_indicator_checker",
            "parameter_pollution_exploitation",
            "auth_header_tampering_variations",
            "locale_debug_toggle_checker",
            "websocket_endpoint_discovery",
            "reflected_xss_probe",
        ],
    },
]

ANALYSIS_CHECK_OPTIONS = analysis_check_options()
