MODULE_OPTIONS = [
    {
        "name": "subfinder",
        "label": "Subfinder",
        "description": "Passive subdomain discovery",
        "kind": "tool",
        "group": "discovery",
        "dependency_hint": "Foundation — other modules depend on discovered subdomains",
    },
    {
        "name": "assetfinder",
        "label": "Assetfinder",
        "description": "Secondary passive subdomain discovery",
        "kind": "tool",
        "group": "discovery",
        "dependency_hint": "Complements subfinder with additional sources",
    },
    {
        "name": "amass",
        "label": "Amass",
        "description": "Passive amass enumeration",
        "kind": "tool",
        "group": "discovery",
        "dependency_hint": "Deep enumeration — slower but thorough",
    },
    {
        "name": "httpx",
        "label": "HTTPX",
        "description": "ProjectDiscovery live host probing",
        "kind": "tool",
        "group": "validation",
        "dependency_hint": "Requires discovery modules — filters live hosts",
        "requires": ["subfinder"],
    },
    {
        "name": "gau",
        "label": "GAU",
        "description": "Archive URL collection",
        "kind": "tool",
        "group": "collection",
        "dependency_hint": "Works best after httpx confirms live hosts",
        "requires": ["httpx"],
    },
    {
        "name": "waybackurls",
        "label": "Waybackurls",
        "description": "Wayback URL collection",
        "kind": "tool",
        "group": "collection",
        "dependency_hint": "Pairs with gau for broader URL coverage",
        "requires": ["httpx"],
    },
    {
        "name": "katana",
        "label": "Katana",
        "description": "Crawler for live hosts",
        "kind": "tool",
        "group": "collection",
        "dependency_hint": "Requires httpx — crawls confirmed live hosts",
        "requires": ["httpx"],
    },
    {
        "name": "nuclei",
        "label": "Nuclei",
        "description": "Template-based scanning",
        "kind": "tool",
        "group": "analysis",
        "dependency_hint": "Benefits from collection modules — more URLs = more scan targets",
        "requires": ["httpx"],
    },
    {
        "name": "screenshots",
        "label": "Screenshots",
        "description": "Browser screenshot capture",
        "kind": "screenshots",
        "group": "output",
        "dependency_hint": "Requires httpx — screenshots live hosts",
        "requires": ["httpx"],
    },
    {
        "name": "cache",
        "label": "Cache",
        "description": "Reuse cached subdomains and URLs",
        "kind": "cache",
        "group": "performance",
        "dependency_hint": "Speeds up repeated runs — skips redundant discovery",
    },
]

MODULE_GROUPS = [
    {
        "name": "discovery",
        "label": "Discovery",
        "description": "Find subdomains and widen initial target coverage.",
        "icon": "🔍",
    },
    {
        "name": "validation",
        "label": "Validation",
        "description": "Confirm which discovered hosts are actually alive.",
        "icon": "✅",
    },
    {
        "name": "collection",
        "label": "Collection",
        "description": "Gather URLs from archives and crawlers.",
        "icon": "🕸️",
    },
    {
        "name": "analysis",
        "label": "Analysis",
        "description": "Run vulnerability-focused checks and templates.",
        "icon": "🧠",
    },
    {
        "name": "performance",
        "label": "Performance",
        "description": "Reuse cached data to speed up repeated runs.",
        "icon": "⚡",
    },
    {
        "name": "output",
        "label": "Output",
        "description": "Capture extra visual artifacts during the run.",
        "icon": "📸",
    },
]

MODE_PRESETS = [
    {
        "name": "fast",
        "label": "Fast",
        "description": "Quicker pass with leaner collection and core scanning.",
        "modules": ["subfinder", "assetfinder", "httpx", "gau", "katana", "nuclei", "cache"],
    },
    {
        "name": "deep",
        "label": "Deep",
        "description": "Broader recon and more collection for richer coverage.",
        "modules": [
            "subfinder",
            "assetfinder",
            "amass",
            "httpx",
            "gau",
            "waybackurls",
            "katana",
            "nuclei",
            "cache",
        ],
    },
    {
        "name": "idor",
        "label": "IDOR-Focused",
        "description": "Biases scoring and follow-up checks toward object reference exposure.",
        "modules": [
            "subfinder",
            "assetfinder",
            "httpx",
            "gau",
            "waybackurls",
            "katana",
            "nuclei",
            "cache",
        ],
    },
    {
        "name": "ssrf",
        "label": "SSRF-Focused",
        "description": "Biases scoring and follow-up checks toward callback and fetch sinks.",
        "modules": [
            "subfinder",
            "assetfinder",
            "httpx",
            "gau",
            "waybackurls",
            "katana",
            "nuclei",
            "cache",
        ],
    },
    {
        "name": "safe",
        "label": "Safe",
        "description": "Lower-volume mode with tighter active checks and conservative analysis limits.",
        "modules": ["subfinder", "assetfinder", "httpx", "gau", "katana", "cache"],
    },
    {
        "name": "aggressive",
        "label": "Aggressive",
        "description": "Higher-volume mode that enables broader collection and deeper active execution.validators.",
        "modules": [
            "subfinder",
            "assetfinder",
            "amass",
            "httpx",
            "gau",
            "waybackurls",
            "katana",
            "nuclei",
            "cache",
        ],
    },
]
