PROGRESS_PREFIX = "PIPELINE_PROGRESS "
STAGE_LABELS = {
    "startup": "Preparing run",
    "subdomains": "Enumerating subdomains",
    "live_hosts": "Probing live hosts",
    "urls": "Collecting URLs",
    "recon_validation": "Validating recon",
    "waf": "Fingerprinting WAF",
    "git_diff_crawl": "Diff crawl",
    "parameters": "Extracting parameters",
    "ranking": "Ranking targets",
    "priority": "Ranking targets",
    "passive_scan": "Passive analysis",
    "active_scan": "Active scanning",
    "semgrep": "Static analysis",
    "nuclei": "Running nuclei",
    "subdomain_takeover": "Subdomain takeover",
    "access_control": "Access control testing",
    "validation": "Validating findings",
    "intelligence": "Intelligence enrichment",
    "threat_modeling": "Threat modeling",
    "reporting": "Building report",
    "sarif_export": "SARIF export",
    "completed": "Completed",
    "shutdown": "Shutting down",
    # Aliases for backward compatibility
    "analysis": "Passive analysis",
}
