import re

TEXTUAL_CONTENT_TYPES = (
    "application/javascript",
    "application/json",
    "application/ld+json",
    "application/xml",
    "application/xhtml+xml",
    "image/svg+xml",
    "text/",
)
IDOR_PARAM_NAMES = {
    "account",
    "account_id",
    "customer",
    "customer_id",
    "doc",
    "document",
    "document_id",
    "file",
    "group",
    "group_id",
    "id",
    "invoice",
    "invoice_id",
    "member",
    "member_id",
    "object",
    "object_id",
    "order",
    "order_id",
    "org",
    "org_id",
    "profile",
    "project",
    "project_id",
    "record",
    "record_id",
    "tenant",
    "tenant_id",
    "user",
    "user_id",
    "uuid",
}
IDOR_PATH_KEYWORDS = (
    "/account",
    "/accounts",
    "/customer",
    "/customers",
    "/document",
    "/documents",
    "/file",
    "/files",
    "/invoice",
    "/invoices",
    "/member",
    "/members",
    "/order",
    "/orders",
    "/org",
    "/orgs",
    "/profile",
    "/profiles",
    "/project",
    "/projects",
    "/record",
    "/records",
    "/tenant",
    "/tenants",
    "/user",
    "/users",
)
UUID_RE = re.compile(
    r"\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b", re.IGNORECASE
)
JWT_RE = re.compile(r"\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b")
SENSITIVE_PATTERNS = (
    ("private_key_block", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("aws_access_key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    (
        "aws_secret_key",
        re.compile(
            r"(?i)\baws(.{0,20})?(secret|access)[_-]?key\b.{0,8}[:=].{0,4}[A-Za-z0-9/+=]{30,}"
        ),
    ),
    ("github_token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{24,}\b")),
    ("openai_api_key", re.compile(r"\bsk-(?:proj-|live-|test-)?[A-Za-z0-9_-]{20,}\b")),
    ("anthropic_api_key", re.compile(r"\bsk-ant-[A-Za-z0-9_-]{20,}\b")),
    ("slack_token", re.compile(r"\bxox[baprs]-[0-9A-Za-z-]{10,}")),
    ("slack_webhook", re.compile(r"https://hooks\.slack\.com/services/[A-Za-z0-9/_-]+")),
    ("stripe_secret", re.compile(r"\bsk_live_[A-Za-z0-9]{16,}\b")),
    ("stripe_publishable", re.compile(r"\bpk_live_[A-Za-z0-9]{16,}\b")),
    ("google_api_key", re.compile(r"\bAIza[0-9A-Za-z\-_]{35}(?![0-9A-Za-z\-_])")),
    ("google_oauth_secret", re.compile(r"\bGOCSPX-[A-Za-z0-9_-]{28}\b")),
    (
        "azure_connection_string",
        re.compile(
            r"(?i)DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88}"
        ),
    ),
    ("sendgrid_api_key", re.compile(r"\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b")),
    ("twilio_auth_token", re.compile(r"\b[a-f0-9]{32}\b")),
    ("bearer_token", re.compile(r"(?i)\bbearer\s+[A-Za-z0-9\-._~+/]+=*")),
    (
        "internal_ip_reference",
        re.compile(r"\b(?:10\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01])|192\.168)\.\d{1,3}\.\d{1,3}\b"),
    ),
    (
        "cloud_metadata_url",
        re.compile(r"(?i)(?:169\.254\.169\.254|metadata\.google\.internal|metadata\.azure\.com)"),
    ),
    (
        "secret_assignment",
        re.compile(
            r"(?i)\b(api[_-]?key|secret|password|passwd|token)\b\s*[:=]\s*['\"][^'\"]{8,}['\"]"
        ),
    ),
)
TOKEN_PARAM_NAMES = {
    "access_token",
    "api_key",
    "apikey",
    "auth",
    "authorization",
    "bearer",
    "code",
    "id_token",
    "jwt",
    "refresh_token",
    "session",
    "sessionid",
    "token",
}
# Common CSRF token field names found in forms, headers, and cookies
CSRF_TOKEN_NAMES = {
    "csrf_token",
    "csrf-token",
    "csrftoken",
    "xsrf_token",
    "xsrf-token",
    "xsrftoken",
    "_token",
    "authenticity_token",
    "csrfmiddlewaretoken",
    "csrf_token_name",
    "token_csrf",
}
EXTERNAL_REFERENCE_RE = re.compile(r"""https?://[A-Za-z0-9._:-]+""")
SSRF_PARAM_NAMES = {
    "callback",
    "continue",
    "data",
    "dest",
    "destination",
    "domain",
    "feed",
    "file",
    "host",
    "image",
    "load",
    "next",
    "path",
    "proxy",
    "redirect",
    "remote_auth_id",
    "reference",
    "resource",
    "return",
    "return_to",
    "site",
    "state",
    "target",
    "uri",
    "url",
    "validate",
    "webhook",
    "profile",
    # Additional SSRF sink parameters commonly found in modern APIs
    "endpoint",
    "fetch",
    "forward",
    "go",
    "href",
    "html",
    "link",
    "location",
    "lookup",
    "nav",
    "open",
    "out",
    "page",
    "portal",
    "ref",
    "request_uri",
    "server",
    "show",
    "source",
    "to",
    "view",
    "window",
}

# Additional CSRF token parameter names used in modern frameworks
ADDITIONAL_CSRF_PARAM_NAMES = {
    "csrf",
    "xsrf",
    "x-csrf-token",
    "x-xsrf-token",
}

TECH_SIGNATURES = (
    ("Cloudflare", re.compile(r"cloudflare", re.IGNORECASE)),
    ("Akamai", re.compile(r"akamai", re.IGNORECASE)),
    ("nginx", re.compile(r"nginx", re.IGNORECASE)),
    ("Apache", re.compile(r"apache", re.IGNORECASE)),
    ("IIS", re.compile(r"iis|asp\.net", re.IGNORECASE)),
    ("WordPress", re.compile(r"wp-content|wordpress", re.IGNORECASE)),
    ("Next.js", re.compile(r"__next|x-nextjs-cache", re.IGNORECASE)),
    ("React", re.compile(r"react|__react", re.IGNORECASE)),
    ("Angular", re.compile(r"ng-version|angular", re.IGNORECASE)),
    ("Vue", re.compile(r"vue", re.IGNORECASE)),
    ("Laravel", re.compile(r"laravel", re.IGNORECASE)),
    ("Django", re.compile(r"django|csrftoken", re.IGNORECASE)),
    ("Ruby on Rails", re.compile(r"rails|rack", re.IGNORECASE)),
)
