VALIDATOR_ORDER: tuple[str, ...] = (
    "redirect",
    "ssrf",
    "token_reuse",
    "idor",
    "csrf",
    "xss",
    "ssti",
    "file_upload",
    "cors",
    "graphql_abuse",
    "jwt_weakness",
    "race_condition",
    "cache_poisoning",
    "saml",
    "oauth",
    "oauth_saml",
)

VALIDATOR_RESULT_KEYS: dict[str, str] = {
    "redirect": "open_redirect_validation",
    "ssrf": "ssrf_validation",
    "token_reuse": "token_reuse_validation",
    "idor": "idor_validation",
    "csrf": "csrf_validation",
    "xss": "xss_validation",
    "ssti": "ssti_validation",
    "file_upload": "file_upload_validation",
    "cors": "cors_validation",
    "graphql_abuse": "graphql_validation",
    "jwt_weakness": "jwt_validation",
    "race_condition": "race_condition_validation",
    "cache_poisoning": "cache_poisoning_validation",
    "saml": "saml_validation",
    "oauth": "oauth_validation",
    "oauth_saml": "oauth_saml_validation",
}
