from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class ArtifactStore(Protocol):
    def put(self, key: str, payload: bytes) -> str: ...

    def get(self, key: str) -> bytes: ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> None: ...

    def list(self, prefix: str = "") -> list[str]: ...


class CheckpointStore(Protocol):
    def write(self, run_id: str, version: int, payload: dict[str, Any]) -> str | Path: ...

    def read_latest(self, run_id: str | None = None) -> dict[str, Any] | None: ...

    def read_version(self, path: str | Path) -> dict[str, Any] | None: ...

    def list_versions(self, run_id: str) -> list[str | Path]: ...

    def delete(self, path: str | Path) -> None: ...


class FindingStore(Protocol):
    def save_many(self, run_id: str, findings: list[dict[str, Any]]) -> None: ...

    def load_many(self, run_id: str) -> list[dict[str, Any]]: ...
