"""WAF/CDN Fingerprints and Patterns.

Centralized patterns for Cloudflare, AWS WAF, Imperva, etc., used for evasion
and detection across multiple layers of the application without architectural
violating purity contracts.
"""

from typing import Any

# WAF/CDN fingerprints based on response headers and content patterns
CDN_WAF_PATTERNS: dict[str, dict[str, Any]] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-connecting-ip"],
        "cookies": ["__cfduid", "__cf_bm"],
        "body": [],
    },
    "AWS CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "cloudfront", "via"],
        "cookies": ["CloudFront-Policy", "CloudFront-Key-Pair-Id", "CloudFront-Signature"],
        "body": ["ERROR: The request could not be satisfied"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-waf-", "x-amzn-requestid"],
        "cookies": [],
        "body": ["blocked by AWS WAF"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "pragma", "akamai-grn", "x-cache-remote"],
        "cookies": ["ak_bmsc", "akavpau", "abck"],
        "body": [],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-timer", "fastly"],
        "cookies": [],
        "body": [],
    },
    "Imperva/Incapsula": {
        "headers": ["X-Iinfo", "Incapsula"],
        "cookies": ["incap_ses", "visid_incap"],
        "body": ["check if you are a human", "incapsula incident"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "sucuri"],
        "cookies": ["sucuri_cloudproxy_uuid"],
        "body": ["sucuri web firewall"],
    },
    "Barracuda WAF": {
        "headers": ["x-barracuda-"],
        "cookies": ["barra_counter_session", "barra_session"],
        "body": [],
    },
    "F5 BIG-IP": {
        "headers": ["X-WA-Info", "X-Cnection"],
        "cookies": ["F5_HT", "F5_Passcode", "LastMRH_Session", "MRHSession"],
        "body": [],
    },
    "ModSecurity": {
        "headers": ["ModSecurity"],
        "cookies": [],
        "body": ["mod_security", "this error was generated by mod_security"],
    },
    "FortiWeb WAF": {
        "headers": ["X-FortiWeb"],
        "cookies": [],
        "body": [],
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-msedge-ref", "x-azure-fd"],
        "cookies": [],
        "body": [],
    },
    "Google Cloud CDN": {
        "headers": ["via"] if "google" in "".lower() else ["x-goog-", "via"],
        "cookies": [],
        "body": [],
    },
    "nginx WAF (NAXSI)": {
        "headers": [],
        "cookies": [],
        "body": ["blocked by naxsi"],
    },
    "Radware AppWall": {
        "headers": ["x-sl-stats"],
        "cookies": [],
        "body": [],
    },
    "StackPath": {
        "headers": ["x-cdn", "x-stackpath"],
        "cookies": [],
        "body": [],
    },
    "Zscaler/ZScaler": {
        "headers": ["X-Zscaler-"],
        "cookies": [],
        "body": [],
    },
}
