"""WAF/CDN Fingerprints and Patterns.

Centralized patterns for Cloudflare, AWS WAF, Imperva, etc., used for evasion
and detection across multiple layers of the application without architectural
violating purity contracts.
"""

from typing import Any

# WAF/CDN fingerprints based on response headers and content patterns
CDN_WAF_PATTERNS: dict[str, dict[str, Any]] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-connecting-ip"],
        "cookies": ["__cfduid", "__cf_bm"],
        "body": [],
    },
    "Cloudflare UAM": {
        "headers": ["cf-ray", "cf-cache-status", "server: cloudflare"],
        "cookies": ["__cfduid", "cf_use_info", "cf_clearance"],
        "body": ["access denied", "attention required", "cloudflare ray id", "please wait", "under attack mode"],
    },
    "Cloudflare WAFChallenge": {
        "headers": ["cf-ray", "server: cloudflare", "set-cookie: cf_clearance"],
        "cookies": ["cf_clearance", "__cfduid"],
        "body": ["please wait", "challenge platform", "ray id", "cloudflare", "access to this site has been limited"],
    },
    "AWS CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "cloudfront", "via"],
        "cookies": ["CloudFront-Policy", "CloudFront-Key-Pair-Id", "CloudFront-Signature"],
        "body": ["ERROR: The request could not be satisfied"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-waf-", "x-amzn-requestid"],
        "cookies": [],
        "body": ["blocked by AWS WAF"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "pragma", "akamai-grn", "x-cache-remote", "x-edge-"],
        "cookies": ["ak_bmsc", "akavpau", "abck"],
        "body": ["reference #", "access denied", "akamai"],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-timer", "fastly"],
        "cookies": [],
        "body": [],
    },
    "Imperva/Incapsula": {
        "headers": ["X-Iinfo", "Incapsula", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap", "incap_ses_", "visid_incap_"],
        "body": ["check if you are a human", "incapsula incident", "_incap_"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "sucuri", "x-sucuri-cache", "cf-bgi"],
        "cookies": ["sucuri_cloudproxy_uuid", "sucuri_cloudproxy"],
        "body": ["sucuri web firewall", "access denied", "cloudproxy"],
    },
    "Barracuda WAF": {
        "headers": ["x-barracuda-"],
        "cookies": ["barra_counter_session", "barra_session"],
        "body": [],
    },
    "F5 BIG-IP": {
        "headers": ["X-WA-Info", "X-Cnection"],
        "cookies": ["F5_HT", "F5_Passcode", "LastMRH_Session", "MRHSession"],
        "body": [],
    },
    "ModSecurity": {
        "headers": ["ModSecurity"],
        "cookies": [],
        "body": ["mod_security", "this error was generated by mod_security"],
    },
    "FortiWeb WAF": {
        "headers": ["X-FortiWeb"],
        "cookies": [],
        "body": [],
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-msedge-ref", "x-azure-fd", "x-fd-", "azure-frontdoor"],
        "cookies": [],
        "body": [],
    },
    "Bunny.net": {
        "headers": ["x-bunny-cdn", "cdn-bunny", "bunnycdn-edge", "x-cache-status"],
        "cookies": ["bunnycdn"],
        "body": [],
    },
    "CDN77": {
        "headers": ["cdn77", "cdn-cgi", "x-cdn77-edge"],
        "cookies": [],
        "body": [],
    },
    "Alibaba Cloud CDN": {
        "headers": ["ali-cdn", "ali-swift-global", "x-alicdn-", "ecd"],
        "cookies": ["_alicdn_"],
        "body": [],
    },
    "Tencent Cloud CDN": {
        "headers": ["tencent-cdn", "x-tencent-"],
        "cookies": ["tencent_sid", "td_cdn"],
        "body": [],
    },
    "Google Cloud CDN": {
        "headers": ["via"] if "google" in "".lower() else ["x-goog-", "via"],
        "cookies": [],
        "body": [],
    },
    "nginx WAF (NAXSI)": {
        "headers": [],
        "cookies": [],
        "body": ["blocked by naxsi"],
    },
    "Radware AppWall": {
        "headers": ["x-sl-stats"],
        "cookies": [],
        "body": [],
    },
    "StackPath": {
        "headers": ["x-cdn", "x-stackpath", "stackpath-cdn", "x-edge-location", "stackpath-cdn"],
        "cookies": ["stackpath", "sp_cdn"],
        "body": [],
    },
    "Zscaler/ZScaler": {
        "headers": ["X-Zscaler-"],
        "cookies": [],
        "body": [],
    },
}
