#!/usr/bin/env node

/**
 * Script to download Google Fonts for self-hosting.
 * Run: node scripts/download-fonts.mjs
 */

import { mkdir, writeFile, readFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONTS_DIR = join(__dirname, '..', 'public', 'fonts');

const FONTS = [
  {
    family: 'Inter',
    weights: [400, 500, 600, 700],
    formats: ['woff2'],
  },
  {
    family: 'JetBrains Mono',
    weights: [400, 500, 600],
    formats: ['woff2'],
  },
];

async function downloadFont(family, weight) {
  const familySlug = family.toLowerCase().replace(/\s+/g, '-');
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weight}&display=swap`;
  
  const response = await fetch(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    },
  });
  
  const css = await response.text();
  const woff2Match = css.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/);
  
  if (woff2Match) {
    const fontResponse = await fetch(woff2Match[1]);
    const fontBuffer = Buffer.from(await fontResponse.arrayBuffer());
    const filename = `${familySlug}-${weight}.woff2`;
    await writeFile(join(FONTS_DIR, filename), fontBuffer);
    console.log(`Downloaded: ${filename}`);
    return { family, weight, filename };
  }
  return null;
}

async function generateCSS(fontFiles) {
  let css = '/* Self-hosted Google Fonts - Generated by download-fonts.mjs */\n';
  
  const grouped = {};
  for (const { family, weight, filename } of fontFiles) {
    if (!grouped[family]) grouped[family] = [];
    grouped[family].push({ weight, filename });
  }
  
  for (const [family, fonts] of Object.entries(grouped)) {
    css += `\n@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-display: swap;\n  src: `;
    const sources = fonts.map(f => `url('/fonts/${f.filename}') format('woff2')`);
    css += sources.join(', ') + ';\n';
    css += `  font-weight: ${fonts.map(f => f.weight).join(' ')};\n}\n`;
  }
  
  return css;
}

async function main() {
  await mkdir(FONTS_DIR, { recursive: true });
  
  const fontFiles = [];
  for (const font of FONTS) {
    for (const weight of font.weights) {
      const result = await downloadFont(font.family, weight);
      if (result) fontFiles.push(result);
    }
  }
  
  const css = await generateCSS(fontFiles);
  await writeFile(join(FONTS_DIR, 'fonts.css'), css);
  console.log('Generated fonts.css');
}

main().catch(console.error);
