"""Raw 4-tuple data for passive analysis plugin specs.

Each tuple: ``(key, label, description, group)``.
Consumed by ``passive.py`` via ``spec(...)``.
"""

_PLUGIN_DATA: tuple[tuple[str, str, str, str], ...] = (
    (
        "sensitive_data_scanner",
        "Sensitive Data Scanner",
        "Look for secrets and sensitive patterns in fetched response bodies.",
        "exposure",
    ),
    (
        "header_checker",
        "Header Checker",
        "Flag missing HSTS, CSP, referrer, permissions, and related response headers.",
        "exposure",
    ),
    (
        "cookie_security_checker",
        "Cookie Security",
        "Inspect Set-Cookie headers for missing Secure, HttpOnly, and SameSite protections.",
        "exposure",
    ),
    (
        "cors_misconfig_checker",
        "Passive CORS Review",
        "Review observed CORS headers for wildcard credentials, null origin allowance, and missing Vary handling.",
        "exposure",
    ),
    (
        "cache_control_checker",
        "Cache Control Review",
        "Flag auth and API responses that look cacheable when they should likely be private or no-store.",
        "exposure",
    ),
    (
        "jsonp_endpoint_checker",
        "JSONP Detector",
        "Spot callback-style JSONP endpoints that can expose cross-origin data to script tags.",
        "redirect",
    ),
    (
        "frontend_config_exposure_checker",
        "Frontend Config Review",
        "Scan frontend responses for exposed config objects, API base URLs, DSNs, and GraphQL hints.",
        "exposure",
    ),
    (
        "directory_listing_checker",
        "Directory Listing",
        "Detect passive signs of exposed directory indexing in fetched responses.",
        "exposure",
    ),
    (
        "debug_artifact_checker",
        "Debug Artifact Review",
        "Flag debug, actuator, swagger, env, and other diagnostic exposure hints from URLs and responses.",
        "exposure",
    ),
    (
        "stored_xss_signal_detector",
        "Stored XSS Signals",
        "Look for dangerous markup inside comment, message, bio, description, and similar response fields.",
        "exposure",
    ),
    (
        "token_leak_detector",
        "Token Leak Detector",
        "Hunt for token-like values and referer leakage across URLs and responses.",
        "session",
    ),
    (
        "csrf_protection_checker",
        "CSRF Protection Checker",
        "Identify state-changing endpoints missing CSRF tokens, SameSite cookies, or anti-CSRF headers.",
        "session",
    ),
    (
        "ssti_surface_detector",
        "SSTI Surface Detector",
        "Detect template engine fingerprints and parameters vulnerable to Server-Side Template Injection.",
        "session",
    ),
    (
        "file_upload_surface_detector",
        "File Upload Surface Detector",
        "Identify endpoints that accept file uploads and may be vulnerable to unrestricted upload attacks.",
        "session",
    ),
    (
        "vulnerable_component_detector",
        "Vulnerable Component Detector",
        "Detect exposed version strings, framework fingerprints, and known vulnerable component indicators.",
        "exposure",
    ),
    (
        "business_logic_tampering_detector",
        "Business Logic Tampering Detector",
        "Detect endpoints with price, quantity, and discount parameters vulnerable to client-side manipulation.",
        "session",
    ),
    (
        "jwt_security_analyzer",
        "JWT Security Analyzer",
        "Analyze JWT tokens for weak algorithms, missing claims, expiration issues, and algorithm confusion vulnerabilities.",
        "session",
    ),
    (
        "ssrf_candidate_finder",
        "SSRF Candidate Finder",
        "Highlight URL and callback-style parameters that look SSRF-relevant.",
        "redirect",
    ),
    (
        "idor_candidate_finder",
        "IDOR Candidate Finder",
        "Score endpoints and identifiers that may expose object reference issues.",
        "idor",
    ),
    (
        "technology_fingerprint",
        "Technology Fingerprint",
        "Infer frameworks and infrastructure hints from headers and response content.",
        "exposure",
    ),
    (
        "anomaly_detector",
        "Anomaly Detector",
        "Surface unusual paths, patterns, and high-signal reconnaissance oddities.",
        "exposure",
    ),
    (
        "response_snapshot_system",
        "Response Snapshots",
        "Capture passive baseline status, headers, length, and key response patterns for endpoints.",
        "session",
    ),
    (
        "response_diff_engine",
        "Response Diff Engine",
        "Compare safe parameter mutations and highlight status, redirect, and content changes.",
        "logic",
    ),
    (
        "flow_detector",
        "Flow Detector",
        "Detect access, auth, oauth, and redirect chains across related endpoints.",
        "redirect",
    ),
    (
        "multi_step_flow_breaking_probe",
        "Multi-Step Flow Breaking",
        "Attempt direct access to later workflow steps and flag flows that appear reachable out of sequence.",
        "logic",
    ),
    (
        "smart_payload_suggestions",
        "Payload Suggestions",
        "Generate non-executing test variants for redirect, ID, token, and callback-style parameters.",
        "logic",
    ),
    (
        "cross_user_access_simulation",
        "Cross-User Access Simulation",
        "Compare the same endpoint across user, account, and tenant-like identity contexts.",
        "access",
    ),
    (
        "role_based_endpoint_comparison",
        "Role-Based Comparison",
        "Highlight same-endpoint differences between user and admin-style role contexts.",
        "access",
    ),
    (
        "privilege_escalation_detector",
        "Privilege Escalation Detector",
        "Apply read-only role or scope parameter changes and watch for unexpected access changes.",
        "access",
    ),
    (
        "access_boundary_tracker",
        "Access Boundary Tracker",
        "Track public, private, and admin transitions across related endpoint variants.",
        "access",
    ),
    (
        "session_reuse_detection",
        "Session Reuse Detection",
        "Spot the same token or session value reused across multiple flows or endpoints.",
        "session",
    ),
    (
        "logout_invalidation_check",
        "Logout Invalidation Check",
        "Check whether protected endpoints still behave as authenticated after logout flows.",
        "session",
    ),
    (
        "multi_endpoint_auth_consistency_check",
        "Auth Consistency Check",
        "Compare related endpoints on the same host for inconsistent auth enforcement.",
        "session",
    ),
    (
        "token_scope_analyzer",
        "Token Scope Analyzer",
        "Summarize scope, role, permission, and token fields that imply granted access.",
        "session",
    ),
    (
        "referer_propagation_tracking",
        "Referer Propagation Tracking",
        "Trace whether sensitive query parameters may leak through referers to other hosts.",
        "session",
    ),
    (
        "sensitive_field_detector",
        "Sensitive Field Detector",
        "Extract email, credential, token, API key, and similar fields from JSON responses.",
        "idor",
    ),
    (
        "nested_object_traversal",
        "Nested Object Traversal",
        "Score deep JSON graphs that often expose identifiers, relationships, or hidden objects.",
        "idor",
    ),
    (
        "endpoint_resource_groups",
        "Endpoint Resource Groups",
        "Cluster URLs into likely resource families for broader object-surface visibility.",
        "idor",
    ),
    (
        "bulk_endpoint_detector",
        "Bulk Endpoint Detector",
        "Highlight collection, search, export, and bulk-oriented endpoints worth closer review.",
        "idor",
    ),
    (
        "pagination_walker",
        "Pagination Walker",
        "Mutate page, offset, and limit parameters to observe neighboring data windows.",
        "idor",
    ),
    (
        "filter_parameter_fuzzer",
        "Filter Parameter Fuzzer",
        "Toggle safe filter parameters and look for hidden states, roles, or global views.",
        "logic",
    ),
    (
        "error_based_inference",
        "Error-Based Inference",
        "Use safe invalid values to extract backend field names and hidden parameter hints.",
        "logic",
    ),
    (
        "state_transition_analyzer",
        "State Transition Analyzer",
        "Mutate state and step parameters to detect before/after workflow mismatches.",
        "logic",
    ),
    (
        "parameter_dependency_tracker",
        "Parameter Dependency Tracker",
        "Track whether price, quantity, discount, scope, and role fields react together.",
        "logic",
    ),
    (
        "flow_integrity_checker",
        "Flow Integrity Checker",
        "Detect repeated or out-of-order flow stages that suggest step skipping.",
        "logic",
    ),
    (
        "race_condition_signal_analyzer",
        "Race Condition Signals",
        "Highlight booking, checkout, claim, coupon, and other stateful endpoints that look concurrency-sensitive.",
        "logic",
    ),
    (
        "version_diffing",
        "Version Diffing",
        "Compare alternate API versions for auth, content, and behavior differences.",
        "logic",
    ),
    (
        "role_context_diff",
        "Role Context Diff",
        "Compare response bodies where role, tenant, or account context parameters already vary.",
        "access",
    ),
    (
        "unauth_access_check",
        "Unauth Access Check",
        "Retry likely read-only endpoints without auth headers and compare whether the same data remains visible.",
        "access",
    ),
    (
        "rate_limit_signal_analyzer",
        "Rate Limit Signals",
        "Review JSON and bulk-style endpoints for missing throttling headers or quota cues.",
        "exposure",
    ),
    (
        "response_size_anomaly_detector",
        "Response Size Anomalies",
        "Flag unusually large responses inside a resource group that may indicate over-broad access.",
        "idor",
    ),
    (
        "response_structure_validator",
        "Response Structure Validator",
        "Detect JSON schema drift, inconsistent field exposure, and conditional response shaping across repeated requests.",
        "idor",
    ),
    (
        "payment_flow_intelligence",
        "Payment Flow Intelligence",
        "Identify checkout, billing, refund, and subscription-oriented routes and parameters.",
        "logic",
    ),
    (
        "payment_provider_detection",
        "Payment Provider Detection",
        "Detect payment provider references that help map logic-sensitive checkout flows.",
        "logic",
    ),
    (
        "behavior_analysis_layer",
        "Behavior Analysis",
        "Replay controlled single-parameter variants, track flow shifts, and store reproducible evidence for review.",
        "logic",
    ),
    (
        "redirect_chain_analyzer",
        "Redirect Chain Analyzer",
        "Summarize redirect hops, cross-host jumps, and final destinations for top endpoints.",
        "redirect",
    ),
    (
        "auth_boundary_redirect_detection",
        "Auth-Boundary Redirects",
        "Compare redirect behavior before and after authentication boundaries are crossed.",
        "redirect",
    ),
    (
        "graphql_introspection_exposure_checker",
        "GraphQL Introspection",
        "Detect exposed GraphQL schema introspection that reveals types, fields, and mutations.",
        "exposure",
    ),
    (
        "graphql_error_leakage_checker",
        "GraphQL Error Leakage",
        "Spot verbose GraphQL errors that reveal backend field names, types, and schema details.",
        "exposure",
    ),
    (
        "openapi_swagger_spec_checker",
        "OpenAPI Or Swagger Exposure",
        "Find exposed API specs and docs that make route, auth, and parameter mapping easier.",
        "exposure",
    ),
    (
        "ai_endpoint_exposure_analyzer",
        "AI Endpoint Exposure",
        "Identify chat, model, embedding, and provider-facing AI endpoints plus key-leak indicators.",
        "exposure",
    ),
    (
        "grpc_reflection_exposure_checker",
        "gRPC Reflection Exposure",
        "Detect reflection-enabled gRPC surfaces that can disclose service and method names.",
        "exposure",
    ),
    (
        "cloud_storage_exposure_checker",
        "Cloud Storage Exposure",
        "Flag public bucket, object, and storage-provider exposure hints in URLs and responses.",
        "exposure",
    ),
    (
        "cloud_metadata_exposure_checker",
        "Cloud Metadata Exposure",
        "Detect cloud provider metadata endpoints (AWS IMDS, GCP, Azure), cloud storage bucket exposure, and exposed infrastructure services (Docker, Kubernetes, Redis, etc.) in URLs and response bodies.",
        "exposure",
    ),
    (
        "subdomain_takeover_indicator_checker",
        "Subdomain Takeover Signals",
        "Highlight dangling-host fingerprints and takeover-style provider responses.",
        "exposure",
    ),
    (
        "service_worker_misconfiguration_checker",
        "Service Worker Review",
        "Inspect service worker scope and caching signals that can affect auth and stale content exposure.",
        "exposure",
    ),
    (
        "csp_weakness_analyzer",
        "CSP Weakness Analyzer",
        "Review Content-Security-Policy for unsafe directives and weak script restrictions.",
        "exposure",
    ),
    (
        "referrer_policy_weakness_checker",
        "Referrer Policy Review",
        "Detect permissive Referrer-Policy configurations that can leak path or query information.",
        "exposure",
    ),
    (
        "hsts_weakness_checker",
        "HSTS Weakness Review",
        "Flag missing, weak, or under-scoped Strict-Transport-Security deployment.",
        "exposure",
    ),
    (
        "dns_misconfiguration_signal_checker",
        "DNS Misconfiguration Signals",
        "Surface passive clues for weak SPF, DMARC, MX, or DNS-related configuration issues.",
        "exposure",
    ),
    (
        "email_leakage_detector",
        "Email Leakage Detector",
        "Extract exposed email addresses for asset correlation and identity-surface review.",
        "exposure",
    ),
    (
        "api_version_disclosure_checker",
        "API Version Disclosure",
        "Detect multiple exposed API versions that are worth comparing for auth and field drift.",
        "exposure",
    ),
    (
        "password_confirmation_checker",
        "Password Confirmation Checker",
        "Flag signup/reset flows that appear to accept password entry without confirmation hints.",
        "exposure",
    ),
    (
        "rate_limit_header_analyzer",
        "Rate-Limit Header Review",
        "Inspect explicit throttling headers and flag endpoints that omit rate-limit cues.",
        "exposure",
    ),
    (
        "cache_poisoning_indicator_checker",
        "Cache Poisoning Indicators",
        "Highlight cacheable responses that reflect forwarded host/proto hints without protective vary semantics.",
        "exposure",
    ),
    (
        "error_stack_trace_detector",
        "Stack Trace Detector",
        "Spot framework stack traces, exception pages, and verbose backend error disclosures.",
        "exposure",
    ),
    (
        "cdn_waf_fingerprint_gap_checker",
        "CDN Or WAF Coverage Gaps",
        "Compare protection signals across responses to find hosts or paths that may bypass edge filtering.",
        "exposure",
    ),
    (
        "public_repo_exposure_checker",
        "Public Repo Exposure",
        "Flag exposed repository metadata, browsable git artifacts, and accidental source availability.",
        "exposure",
    ),
    (
        "backup_file_exposure_checker",
        "Backup File Exposure",
        "Find accessible backups, archives, and editor swap-style files on web-facing paths.",
        "exposure",
    ),
    (
        "environment_file_exposure_checker",
        "Environment File Exposure",
        "Detect exposed `.env` and config-like files that may leak credentials or internal settings.",
        "exposure",
    ),
    (
        "log_file_exposure_checker",
        "Log File Exposure",
        "Flag accessible log endpoints and debug-output artifacts that may leak internal data.",
        "exposure",
    ),
    (
        "websocket_endpoint_discovery",
        "WebSocket Discovery",
        "Surface WebSocket endpoints for follow-up auth, origin, and channel-behavior review.",
        "exposure",
    ),
    (
        "http_method_exposure_checker",
        "HTTP Method Exposure",
        "Review advertised Allow methods and method exposure hints in passive responses.",
        "exposure",
    ),
    (
        "parameter_pollution_indicator_checker",
        "Parameter Pollution Signals",
        "Find duplicate-parameter and merge-order indicators that deserve follow-up testing.",
        "exposure",
    ),
    (
        "locale_debug_toggle_checker",
        "Locale Or Debug Toggles",
        "Highlight `debug`, locale, and verbosity-style parameters that can unlock alternate behavior.",
        "exposure",
    ),
    (
        "third_party_key_exposure_checker",
        "Third-Party Key Exposure",
        "Detect exposed external service keys and tokens that may widen the attack surface.",
        "exposure",
    ),
    (
        "json_response_parser",
        "JSON Response Parser",
        "Parse JSON responses into endpoint, field, depth, and nested-object summaries for review.",
        "idor",
    ),
    (
        "json_schema_inference",
        "JSON Schema Inference",
        "Aggregate recurring JSON fields, types, and paths to reveal shared object shapes across endpoints.",
        "idor",
    ),
    (
        "cross_tenant_pii_risk_analyzer",
        "Cross-Tenant PII Risk",
        "Highlight responses that combine tenant or account identity fields with high-value PII fields.",
        "access",
    ),
    (
        "server_side_injection_surface_analyzer",
        "Server-Side Injection Surface",
        "Flag SQLi, file inclusion, XXE, command, and RCE-style parameter surfaces from passive evidence.",
        "logic",
    ),
    (
        "dns_record_analyzer",
        "DNS Record Analyzer",
        "Check for DNS misconfiguration signals, dangling CNAMEs, third-party domain exposure, and CDN/WAF provider detection.",
        "exposure",
    ),
    (
        "ldap_injection_surface_analyzer",
        "LDAP Injection Surface Analyzer",
        "Detect LDAP injection surface indicators in URLs and response bodies, including LDAP parameters, error messages, and authentication endpoints.",
        "passive",
    ),
    (
        "token_lifetime_analyzer",
        "Token Lifetime Analyzer",
        "Analyze authentication tokens for lifetime, rotation, algorithm, and exposure issues across responses.",
        "passive",
    ),
    (
        "oauth_misconfiguration_detector",
        "OAuth Misconfiguration Detector",
        "Passively analyze OAuth/SAML endpoints for implicit flow, missing PKCE, token exposure, missing state, open redirect, scope over-permissioning, and client ID exposure.",
        "passive",
    ),
    (
        "xxe_surface_detector",
        "XXE Surface Detector",
        "Detect XML processing endpoints, SOAP/XML-RPC services, SAML endpoints, RSS/Atom feeds, and XXE error patterns in responses.",
        "passive",
    ),
    (
        "open_redirect_detector",
        "Open Redirect Detector",
        "Identify redirect parameters, meta refresh tags, JavaScript redirects, and Location header issues that may enable open redirect attacks.",
        "passive",
    ),
    (
        "clickjacking_detector",
        "Clickjacking Detector",
        "Detect missing or weak X-Frame-Options, missing CSP frame-ancestors, absent frame-busting JavaScript, and iframe-susceptible endpoints.",
        "passive",
    ),
    (
        "logging_failure_detector",
        "Logging Security Detector",
        "Find log file exposure, logging endpoints, sensitive data in URLs, verbose logging headers, and debug logging indicators in responses.",
        "passive",
    ),
)

__all__ = ["_PLUGIN_DATA"]
