from .base import AnalysisPluginSpec, spec

ACTIVE_PLUGIN_SPECS: tuple[AnalysisPluginSpec, ...] = (
    spec(
        "rate_limit_bypass_detector",
        "Rate Limit Bypass Detector",
        "Test rate limiting enforcement and detect bypass via header manipulation (X-Forwarded-For, X-Real-IP).",
        "active",
    ),
    spec(
        "http_smuggling_detector",
        "HTTP Smuggling Detector",
        "Test for HTTP request smuggling vulnerabilities via Transfer-Encoding/Content-Length header confusion.",
        "active",
    ),
    spec(
        "parameter_pollution_exploitation",
        "Parameter Pollution Exploitation",
        "Replay duplicate query parameters with alternate values and compare which server-side interpretation wins.",
        "active",
    ),
    spec(
        "auth_header_tampering_variations",
        "Auth Header Tampering",
        "Retry endpoints with stripped, invalid, and alternate auth headers to detect inconsistent enforcement.",
        "active",
    ),
    spec(
        "http_method_override_probe",
        "HTTP Method Override Probe",
        "Test X-HTTP-Method-Override and similar headers for method-level access control bypass.",
        "active",
    ),
    spec(
        "json_mutation_attacks",
        "JSON Mutation Attacks",
        "Swap query values for JSON-like objects, arrays, and booleans on API endpoints and compare responses.",
        "active",
    ),
    spec(
        "post_body_mutation_attacks",
        "POST Body Mutation Attacks",
        "Test POST body parameters for type confusion, null injection, prototype pollution, and boundary value vulnerabilities.",
        "active",
    ),
    spec(
        "options_method_probe",
        "OPTIONS Probe",
        "Send low-risk OPTIONS requests to spot exposed unsafe methods and TRACE support.",
        "active",
    ),
    spec(
        "origin_reflection_probe",
        "Origin Reflection Probe",
        "Send a controlled Origin header to detect reflected or credentialed CORS responses.",
        "active",
    ),
    spec(
        "head_method_probe",
        "HEAD Method Probe",
        "Compare GET and HEAD responses for odd status or header mismatches on high-value endpoints.",
        "active",
    ),
    spec(
        "cors_preflight_probe",
        "CORS Preflight Probe",
        "Send a safe OPTIONS preflight to detect permissive methods and headers in CORS policy.",
        "active",
    ),
    spec(
        "trace_method_probe",
        "TRACE Method Probe",
        "Send a low-volume TRACE request to see whether the method is unexpectedly accepted.",
        "active",
        enabled_by_default=False,
    ),
    spec(
        "reflected_xss_probe",
        "Reflected Input Probe",
        "Send a harmless marker through text parameters and look for reflected input sinks in responses.",
        "active",
    ),
    spec(
        "sqli_safe_probe",
        "SQLi Safe Probe",
        "Send safe SQL test payloads to SQL-relevant parameters and detect error-based SQL injection responses.",
        "active",
    ),
    spec(
        "graphql_active_probe",
        "GraphQL Active Probe",
        "Send safe GraphQL queries to enumerate schemas, test batch abuse, and detect mutation surfaces.",
        "active",
    ),
    spec(
        "graphql_introspection_check",
        "GraphQL Introspection & Schema Test",
        "Detect GraphQL endpoints, test schema introspection exposure, query depth abuse, batch aliasing, and mutation surfaces.",
        "active",
    ),
    spec(
        "http_smuggling_probe",
        "HTTP Smuggling Probe",
        "Actively probe for CL.TE, TE.CL, and double Content-Length smuggling via header conflict requests.",
        "active",
    ),
    spec(
        "http2_probe",
        "HTTP/2 Probe",
        "Test HTTP/2 downgrade attacks, rapid reset, and h2c upgrade acceptance.",
        "active",
    ),
    spec(
        "oauth_flow_analyzer",
        "OAuth Flow Analyzer",
        "Analyze OAuth/SAML endpoints for implicit flow, missing PKCE, open redirect, and token exposure.",
        "active",
    ),
    spec(
        "websocket_message_probe",
        "WebSocket Probe",
        "Probe WebSocket endpoints for missing auth, origin bypass, and arbitrary message acceptance.",
        "active",
    ),
    spec(
        "path_traversal_active_probe",
        "Path Traversal Probe",
        "Test parameters with directory traversal sequences including encoded variants.",
        "active",
    ),
    spec(
        "command_injection_active_probe",
        "Command Injection Probe",
        "Send OS command injection payloads to command-relevant parameters.",
        "active",
    ),
    spec(
        "xxe_active_probe",
        "XXE Active Probe",
        "Send crafted XML bodies with external entity declarations to XML-content endpoints.",
        "active",
    ),
    spec(
        "application_ssrf_vector_detector",
        "Application SSRF Vector Detector",
        "Detect Grafana, Kibana, Jenkins, GitLab, and other apps with known SSRF-prone endpoints.",
        "active",
    ),
    spec(
        "proxy_ssrf_probe",
        "Proxy SSRF Probe",
        "Detect SSRF vulnerabilities via HTTP proxy configuration abuse, proxy path injection, and forward proxy misconfiguration.",
        "active",
    ),
    spec(
        "ssrf_active_probe",
        "SSRF Active Probe",
        "Actively test URL parameters with internal and collaborator-style payloads.",
        "active",
    ),
    spec(
        "open_redirect_active_probe",
        "Open Redirect Probe",
        "Test redirect and callback parameters with external URL payloads.",
        "active",
    ),
    spec(
        "crlf_injection_probe",
        "CRLF Injection Probe",
        "Test parameters for response splitting and header injection via CRLF sequences.",
        "active",
    ),
    spec(
        "host_header_injection_probe",
        "Host Header Probe",
        "Manipulate Host and X-Forwarded-Host headers to test for poisoning.",
        "active",
    ),
    spec(
        "ssti_active_probe",
        "SSTI Active Probe",
        "Send template injection payloads to template-relevant parameters.",
        "active",
    ),
    spec(
        "nosql_injection_probe",
        "NoSQL Injection Probe",
        "Test JSON body parameters with MongoDB-style operator payloads.",
        "active",
    ),
    spec(
        "deserialization_probe",
        "Deserialization Probe",
        "Send crafted serialized objects to parameters that look like serialized data.",
        "active",
    ),
    spec(
        "clickjacking_test",
        "Clickjacking Active Test",
        "Actively test endpoints for clickjacking vulnerabilities by checking missing framing protections and testing actual framing behavior.",
        "active",
    ),
    spec(
        "ssrf_oob_validator",
        "SSRF Out-of-Band Validator",
        "Actively test URL parameters with internal and collaborator-style payloads for SSRF vulnerabilities.",
        "active",
    ),
    spec(
        "mass_assignment_detector",
        "Mass Assignment Detector",
        "Actively test POST/PUT endpoints for mass assignment vulnerabilities by injecting sensitive fields into JSON request bodies and comparing responses.",
        "active",
    ),
    spec(
        "cache_deception_probe",
        "Cache Deception Probe",
        "Actively test for web cache deception by requesting sensitive endpoints with static file extensions and path normalization tricks, checking for cacheable responses containing user-specific data.",
        "active",
    ),
    spec(
        "email_header_injection_probe",
        "Email Header Injection Probe",
        "Test email-related parameters for CRLF injection vulnerabilities that could allow header injection into outbound emails.",
        "active",
    ),
    spec(
        "xml_bomb_detector",
        "XML Bomb Detector",
        "Detect XML entity expansion (Billion Laughs, Quadratic Blowup) and XXE vulnerabilities in XML-processing endpoints.",
        "active",
    ),
    spec(
        "deserialization_language_probe",
        "Deserialization Language Probe",
        "Detect language-specific deserialization formats and test for insecure deserialization across multiple serialization libraries.",
        "active",
    ),
    spec(
        "csrf_active_probe",
        "CSRF Active Probe",
        "Test state-changing endpoints for missing CSRF protections via token omission, invalid tokens, and Origin/Referer bypass attempts.",
        "active",
    ),
    spec(
        "xpath_injection_probe",
        "XPath Injection Probe",
        "Send XPath injection payloads to XML-backed endpoint parameters and detect error patterns, auth bypass, and response divergence.",
        "active",
    ),
    spec(
        "hpp_active_probe",
        "HTTP Parameter Pollution Probe",
        "Test endpoints with duplicate parameters, encoded variants, and array-style formatting to detect parameter parsing inconsistencies.",
        "active",
    ),
    spec(
        "jwt_manipulation_probe",
        "JWT Manipulation Probe",
        "Test algorithm confusion, none algorithm attack, claim modification, kid path traversal, jku injection, and expired token acceptance.",
        "active",
    ),
    spec(
        "websocket_hijacking_probe",
        "WebSocket Hijacking Probe",
        "Test WebSocket endpoints for cross-origin acceptance, missing origin validation, and authentication bypass.",
        "active",
    ),
    spec(
        "idor_active_probe",
        "IDOR Active Probe",
        "Test numeric IDs, UUIDs, and object reference parameters for insecure direct object reference vulnerabilities via ID manipulation.",
        "active",
    ),
    spec(
        "file_upload_active_probe",
        "File Upload Active Probe",
        "Test upload endpoints with dangerous extensions, double extensions, null bytes, MIME manipulation, magic bytes, and polyglot files.",
        "active",
    ),
    spec(
        "cookie_manipulation_probe",
        "Cookie Manipulation Probe",
        "Test cookie tampering, flag removal, base64/JSON decoding, session fixation, overflow, and injection of privileged cookie names.",
        "active",
    ),
    spec(
        "auth_bypass_check",
        "Auth Bypass Active Check",
        "Actively test endpoints for authentication bypass via JWT stripping, cookie manipulation, and parameter injection.",
        "active",
    ),
    spec(
        "tenant_isolation_check",
        "Tenant Isolation Check",
        "Detect multi-tenant applications and test tenant isolation for horizontal and vertical privilege escalation vulnerabilities.",
        "active",
    ),
    spec(
        "access_control_analyzer",
        "Access Control Analyzer",
        "Automated authorization bypass detection inspired by Autorize. Tests endpoints with no auth and invalid tokens, comparing responses to detect enforcement failures.",
        "active",
    ),
)
