export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  TARGETS: '/targets',
  JOBS: '/jobs',
  JOB_DETAIL: '/jobs/:id',
  FINDINGS: '/findings',
  BUG_BOUNTY: '/bug-bounty',
  PIPELINE: '/pipeline',
  SETTINGS: '/settings',
  COCKPIT: '/cockpit',
  REPLAY: '/replay',
  CACHE_MANAGEMENT: '/cache-management',
  RISK_SCORE: '/risk-score',
  FINDINGS_TIMELINE: '/findings-timeline',
  TARGET_COMPARISON: '/target-comparison',
  SCAN_DIFF: '/scan-diff',
  REMEDIATION_PLANNER: '/remediation-planner',
  DETECTION_QUALITY: '/detection-quality',
  GAP_ANALYSIS: '/gap-analysis',
  LEARNING: '/learning',
  MESH: '/mesh',
  SECURITY: '/security',
  TRACING: '/tracing',
  AUDIT_LOGS: '/audit-logs',
  COMPLIANCE: '/compliance',
  REPORTS: '/reports',
  REPORTS_BUILDER: '/reports/builder',
  ACCESS_LOGS: '/access-logs',
  EVIDENCE_CUSTODY: '/evidence-custody',
  EVIDENCE_CUSTODY_DETAIL: '/evidence-custody/:evidenceId',
  SELF_HEALING: '/self-healing',
  EVASION: '/evasion',
  RISK_ACCEPTANCE: '/risk/acceptance',
  RISK_ASSETS: '/risk/assets',
  RISK_HUB: '/risk',
  GOVERNANCE_HUB: '/governance',
  ANALYTICS_HUB: '/analytics',
  TRACE_REDIRECT: '/trace',
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
