"""CDN/WAF detection module for recon pipeline.

Identifies Content Delivery Networks (CDNs) and Web Application Firewalls
(WAFs) protecting target hosts. This information is critical because:
- CDN origins may be discovered and bypass the CDN entirely
- WAF presence affects exploitability scoring
- Different WAFs have different bypass techniques
- CDN edge servers vs origin servers have different security postures
"""

import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# WAF/CDN fingerprints based on response headers and content patterns
CDN_WAF_PATTERNS: dict[str, dict[str, Any]] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-connecting-ip"],
        "cookies": ["__cfduid", "__cf_bm"],
        "body": [],
    },
    "AWS CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "cloudfront", "via"],
        "cookies": ["CloudFront-Policy", "CloudFront-Key-Pair-Id", "CloudFront-Signature"],
        "body": ["ERROR: The request could not be satisfied"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-waf-", "x-amzn-requestid"],
        "cookies": [],
        "body": ["blocked by AWS WAF"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "pragma", "akamai-grn", "x-cache-remote"],
        "cookies": ["ak_bmsc", "akavpau", "abck"],
        "body": [],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-timer", "fastly"],
        "cookies": [],
        "body": [],
    },
    "Imperva/Incapsula": {
        "headers": ["X-Iinfo", "Incapsula"],
        "cookies": ["incap_ses", "visid_incap"],
        "body": ["check if you are a human", "incapsula incident"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "sucuri"],
        "cookies": ["sucuri_cloudproxy_uuid"],
        "body": ["sucuri web firewall"],
    },
    "Barracuda WAF": {
        "headers": ["x-barracuda-"],
        "cookies": ["barra_counter_session", "barra_session"],
        "body": [],
    },
    "F5 BIG-IP": {
        "headers": ["X-WA-Info", "X-Cnection"],
        "cookies": ["F5_HT", "F5_Passcode", "LastMRH_Session", "MRHSession"],
        "body": [],
    },
    "ModSecurity": {
        "headers": ["ModSecurity"],
        "cookies": [],
        "body": ["mod_security", "this error was generated by mod_security"],
    },
    "FortiWeb WAF": {
        "headers": ["X-FortiWeb"],
        "cookies": [],
        "body": [],
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-msedge-ref", "x-azure-fd"],
        "cookies": [],
        "body": [],
    },
    "Google Cloud CDN": {
        "headers": ["via"] if "google" in "".lower() else ["x-goog-", "via"],
        "cookies": [],
        "body": [],
    },
    "nginx WAF (NAXSI)": {
        "headers": [],
        "cookies": [],
        "body": ["blocked by naxsi"],
    },
    "Radware AppWall": {
        "headers": ["x-sl-stats"],
        "cookies": [],
        "body": [],
    },
    "StackPath": {
        "headers": ["x-cdn", "x-stackpath"],
        "cookies": [],
        "body": [],
    },
    "Zscaler/ZScaler": {
        "headers": ["X-Zscaler-"],
        "cookies": [],
        "body": [],
    },
}


async def detect_waf_cdn(
    urls: list[str],
    timeout: float = 10.0,
    max_urls: int = 100,
) -> list[dict[str, Any]]:
    """Detect CDN/WAF presence for a list of URLs.

    Analyzes response headers, cookies, and body content against known
    patterns for major CDN and WAF providers.

    Args:
        urls: List of URLs to test.
        timeout: Per-request timeout in seconds.
        max_urls: Maximum number of URLs to test.

    Returns:
        List of finding dicts with keys: url, provider, detection_method,
        confidence, details.
    """
    if not urls:
        return []

    results: list[dict[str, Any]] = []

    async with httpx.AsyncClient(
        timeout=timeout,
        follow_redirects=True,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (compatible; cyber-pipeline/1.0; +https://github.com/cyber-pipeline)"
            ),
        },
    ) as client:
        for url in urls[:max_urls]:
            try:
                resp = await client.get(url)
                findings = _analyze_response(url, resp)
                results.extend(findings)
            except httpx.RequestError:
                continue

    logger.info(
        "CDN/WAF detection: tested %d URLs, found %d providers",
        min(len(urls), max_urls),
        len(results),
    )
    return results


def _analyze_response(
    url: str,
    resp: httpx.Response,
) -> list[dict[str, Any]]:
    """Analyze a single HTTP response for WAF/CDN signatures."""
    findings: list[dict[str, Any]] = []

    headers_lower = {k.lower(): v for k, v in resp.headers.items()}
    cookies_lower = {k.lower(): v for k, v in resp.cookies.items()}
    body_lower = (resp.text or "").lower()

    for provider, patterns in CDN_WAF_PATTERNS.items():
        header_score = 0
        cookie_score = 0
        body_score = 0

        # Check headers
        header_patterns = patterns.get("headers", [])
        for pattern in header_patterns:
            if any(pattern.lower() in h for h in headers_lower):
                header_score += 1

        # Check cookies
        cookie_patterns = patterns.get("cookies", [])
        for pattern in cookie_patterns:
            if pattern.lower() in cookies_lower:
                cookie_score += 1

        # Check body
        body_patterns = patterns.get("body", [])
        for pattern in body_patterns:
            if pattern.lower() in body_lower:
                body_score += 1

        total_score = header_score + cookie_score + body_score
        if total_score > 0:
            # Determine detection method and confidence
            if header_score > 0 and cookie_score > 0:
                method = "headers+cookies"
                confidence = 1.0
            elif header_score > 0:
                method = "headers"
                confidence = 0.9
            elif cookie_score > 0:
                method = "cookies"
                confidence = 0.8
            else:
                method = "body"
                confidence = 0.7

            findings.append(
                {
                    "url": url,
                    "provider": provider,
                    "detection_method": method,
                    "confidence": confidence,
                    "details": {
                        "header_matches": min(header_score, len(header_patterns)),
                        "cookie_matches": min(cookie_score, len(cookie_patterns)),
                        "body_matches": min(body_score, len(body_patterns)),
                        "server_header": headers_lower.get("server", ""),
                    },
                }
            )

    return findings


def build_waf_cdn_report(
    findings: list[dict[str, Any]],
) -> dict[str, Any]:
    """Build a structured WAF/CDN report from detection results.

    Args:
        findings: Detection findings from detect_waf_cdn.

    Returns:
        Report dict with per-provider counts and URL breakdowns.
    """
    by_provider: dict[str, list[str]] = {}
    total_urls_tested = 0
    urls_with_waf: set[str] = set()

    for finding in findings:
        url = finding["url"]
        provider = finding["provider"]
        by_provider.setdefault(provider, []).append(url)
        urls_with_waf.add(url)

    total_urls_tested = len(urls_with_waf)
    unique_providers = set(by_provider.keys())

    return {
        "total_urls_tested": total_urls_tested,
        "urls_protected": len(urls_with_waf),
        "unique_providers": sorted(unique_providers),
        "by_provider": {
            provider: {"urls": urls, "count": len(urls)} for provider, urls in by_provider.items()
        },
    }
