export const APP_VERSION = '2.0.0';

export const FEATURE_FLAGS = {
  ENABLE_NOTIFICATION_DIGEST: import.meta.env.VITE_ENABLE_NOTIFICATION_DIGEST === 'true',
  NOTIFICATION_DIGEST_MAX_ITEMS: parseInt(import.meta.env.VITE_NOTIFICATION_DIGEST_MAX_ITEMS || '50', 10),
  NOTIFICATION_DIGEST_THROTTLE_MS: parseInt(import.meta.env.VITE_NOTIFICATION_DIGEST_THROTTLE_MS || '30000', 10),
} as const;
