"""WAF-aware probe payload adapter.

Active probes (XSS, SQLi, SSTI, SSRF, etc.) send payloads that are
detected and blocked by modern WAFs (Cloudflare, Akamai, ModSecurity,
Imperva). The evasion strategies live in
:mod:`src.detection.waf.strategies`, but until this module existed
they were not applied to the active probes generated by the
validators.

This adapter wraps an outgoing probe request and rewrites the URL
parameters, headers, and body using the configured
:class:`StrategyBundle`. The order of strategies is configurable
(``strategy_order``) so operators can tune it per-target.

Configuration (under ``extensions.blackbox_validation.waf_evasion``)::

    {
        "auto_apply": true,
        "strategy_order": ["unicode_normalization", "comment_injection",
                           "double_encoding", "case_swap"],
        "per_category": {
            "sqli": ["double_encoding", "comment_injection_sql"],
            "xss": ["unicode_normalization", "case_swap", "comment_injection_html"]
        }
    }
"""

from __future__ import annotations

import logging
from collections.abc import Iterable
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

from src.detection.waf.strategies import (
    StrategyBundle,
    case_swap,
    comment_injection_html,
    comment_injection_sql,
    double_encode,
    double_encode_path,
    unicode_normalize,
)

logger = logging.getLogger(__name__)


@dataclass(slots=True)
class WafEvasionConfig:
    """Configuration for the WAF-aware probe adapter.

    Attributes:
        auto_apply: When True, the dispatcher applies the configured
            strategy order automatically. When False the adapter
            becomes a no-op and strategies are only available
            on-demand.
        strategy_order: Strategy names to apply (in order) to all
            probes whose category does not have a per-category
            override. Supported names match the helpers exposed by
            :mod:`src.detection.waf.strategies`.
        per_category: Optional override of ``strategy_order`` keyed
            by finding category (e.g. ``sqli``, ``xss``, ``ssti``,
            ``ssrf``).
    """

    auto_apply: bool = True
    strategy_order: list[str] = field(
        default_factory=lambda: [
            "unicode_normalization",
            "comment_injection",
            "double_encoding",
        ]
    )
    per_category: dict[str, list[str]] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> WafEvasionConfig:
        if not isinstance(data, dict):
            return cls()
        auto_apply = bool(data.get("auto_apply", True))
        order = data.get("strategy_order")
        if not isinstance(order, list) or not order:
            order = [
                "unicode_normalization",
                "comment_injection",
                "double_encoding",
            ]
        per_cat = data.get("per_category") or {}
        per_cat_clean: dict[str, list[str]] = {}
        if isinstance(per_cat, dict):
            for k, v in per_cat.items():
                if isinstance(v, list):
                    per_cat_clean[str(k)] = [str(x) for x in v if isinstance(x, str)]
        return cls(
            auto_apply=auto_apply,
            strategy_order=[str(x) for x in order if isinstance(x, str)],
            per_category=per_cat_clean,
        )


def _apply_strategy(value: str, strategy: str) -> str:
    """Apply a single named strategy to ``value``.

    Returns the original value unchanged when the strategy is
    unknown so unknown strategies are silently ignored (operators
    can rename them in config without breaking the adapter).
    """
    if not value:
        return value
    try:
        if strategy == "double_encoding":
            return double_encode(value)
        if strategy == "double_encoding_path":
            return double_encode_path(value)
        if strategy == "unicode_normalization":
            return unicode_normalize(value)
        if strategy == "case_swap":
            return case_swap(value)
        if strategy == "comment_injection_sql":
            return comment_injection_sql(value)
        if strategy == "comment_injection_html":
            return comment_injection_html(value)
        if strategy == "comment_injection":
            # Generic: pick SQL comment style by default; category
            # override routes to the HTML variant.
            return comment_injection_sql(value)
    except Exception as exc:
        logger.debug("WafAwareProbeAdapter: strategy %s failed: %s", strategy, exc)
    return value


def _select_strategies(config: WafEvasionConfig, category: str | None) -> list[str]:
    if category and category in config.per_category:
        return list(config.per_category[category])
    return list(config.strategy_order)


def _rewrite_query(url: str, strategies: Iterable[str]) -> str:
    parsed = urlparse(url)
    if not parsed.query:
        return url
    pairs = parse_qsl(parsed.query, keep_blank_values=True)
    if not pairs:
        return url
    new_pairs: list[tuple[str, str]] = []
    for k, v in pairs:
        for strat in strategies:
            k = _apply_strategy(k, strat)
            v = _apply_strategy(v, strat)
        new_pairs.append((k, v))
    new_query = urlencode(new_pairs, doseq=False)
    return urlunparse(parsed._replace(query=new_query))


def _rewrite_path(url: str, strategies: Iterable[str]) -> str:
    parsed = urlparse(url)
    if not parsed.path or parsed.path == "/":
        return url
    new_path = parsed.path
    for strat in strategies:
        if strat in ("double_encoding", "double_encoding_path"):
            new_path = _apply_strategy(new_path, "double_encoding_path")
    return urlunparse(parsed._replace(path=new_path))


def _rewrite_body(body: str | None, strategies: Iterable[str]) -> str | None:
    if body is None:
        return None
    out = body
    for strat in strategies:
        out = _apply_strategy(out, strat)
    return out


def _rewrite_header_value(value: str, strategies: Iterable[str]) -> str:
    out = value
    for strat in strategies:
        out = _apply_strategy(out, strat)
    return out


class WafAwareProbeAdapter:
    """Apply :class:`StrategyBundle` strategies to active probe requests.

    The adapter is constructed once and shared across probes. It is
    safe to call from concurrent tasks; the underlying strategies are
    pure functions and the configuration is immutable after
    construction.
    """

    def __init__(
        self,
        config: WafEvasionConfig | None = None,
        *,
        bundle: StrategyBundle | None = None,
    ) -> None:
        self._config = config or WafEvasionConfig()
        # The bundle is currently informational — the actual
        # strategies are applied by name from ``strategy_order``.
        # We keep the reference so the adapter can be wired into the
        # existing WAF fingerprinting pipeline that produces
        # ``StrategyBundle`` instances.
        self._bundle = bundle

    @classmethod
    def from_config_block(
        cls, data: dict[str, Any] | None, bundle: StrategyBundle | None = None
    ) -> WafAwareProbeAdapter:
        return cls(WafEvasionConfig.from_dict(data), bundle=bundle)

    @property
    def config(self) -> WafEvasionConfig:
        return self._config

    def strategies_for(self, category: str | None) -> list[str]:
        """Return the resolved strategy list for ``category``."""
        if not self._config.auto_apply:
            return []
        return _select_strategies(self._config, category)

    def adapt_url(self, url: str, *, category: str | None = None) -> str:
        """Return the URL with query and path values rewritten.

        When ``auto_apply`` is ``False`` or no strategies match, the
        URL is returned unchanged. Otherwise the query string is
        rewritten with the per-category strategy order, and the path
        is double-encoded when ``double_encoding`` is enabled.
        """
        strategies = self.strategies_for(category)
        if not strategies:
            return url
        try:
            url = _rewrite_query(url, strategies)
            url = _rewrite_path(url, strategies)
        except Exception as exc:
            logger.debug("WafAwareProbeAdapter: URL rewrite failed for %s: %s", url, exc)
        return url

    def adapt_body(
        self, body: str | None, *, category: str | None = None
    ) -> str | None:
        strategies = self.strategies_for(category)
        if not strategies or body is None:
            return body
        try:
            return _rewrite_body(body, strategies)
        except Exception as exc:
            logger.debug("WafAwareProbeAdapter: body rewrite failed: %s", exc)
            return body

    def adapt_headers(
        self,
        headers: dict[str, str] | None,
        *,
        category: str | None = None,
    ) -> dict[str, str]:
        strategies = self.strategies_for(category)
        if not strategies or not headers:
            return dict(headers or {})
        out: dict[str, str] = {}
        try:
            for k, v in headers.items():
                # Don't transform hop-by-hop / unsafe headers.
                if k.lower() in {"host", "content-length", "transfer-encoding"}:
                    out[k] = v
                    continue
                out[k] = _rewrite_header_value(v, strategies)
        except Exception as exc:
            logger.debug("WafAwareProbeAdapter: header rewrite failed: %s", exc)
            return dict(headers)
        return out

    def adapt_request(
        self,
        url: str,
        *,
        method: str = "GET",
        headers: dict[str, str] | None = None,
        body: str | None = None,
        category: str | None = None,
    ) -> dict[str, Any]:
        """Return a new ``{url, method, headers, body}`` dict.

        This is the helper that active probes should call before
        issuing their request. The original arguments are never
        mutated.
        """
        return {
            "url": self.adapt_url(url, category=category),
            "method": method,
            "headers": self.adapt_headers(headers, category=category),
            "body": self.adapt_body(body, category=category),
        }


# A small allowlist of "safe" transformation categories. Used by
# callers that need a fast yes/no answer for "should I apply evasion
# to this probe category?" (e.g. low-risk recon vs. high-risk
# exploit).
_EVASION_CATEGORY_ALLOWLIST = {
    "sqli",
    "xss",
    "ssti",
    "ssrf",
    "xxe",
    "rce",
    "command_injection",
    "open_redirect",
    "crlf_injection",
    "path_traversal",
    "nosql_injection",
    "deserialization",
    "header_injection",
    "http_smuggling",
}


def evasion_applicable(category: str | None) -> bool:
    """Return True if the category benefits from WAF-evasion rewrites."""
    if not category:
        return False
    return category.lower() in _EVASION_CATEGORY_ALLOWLIST


# Public, high-level helper so callers don't have to import the
# dataclass when they only need one-shot rewriting.
def adapt_probe(
    url: str,
    *,
    body: str | None = None,
    headers: dict[str, str] | None = None,
    category: str | None = None,
    config: WafEvasionConfig | None = None,
) -> dict[str, Any]:
    """Convenience wrapper around :class:`WafAwareProbeAdapter`."""
    adapter = WafAwareProbeAdapter(config or WafEvasionConfig())
    return adapter.adapt_request(
        url, headers=headers, body=body, category=category
    )
