"""Constants and patterns for vulnerable components detection."""

__all__ = [
    "SERVER_VERSION_PATTERNS",
    "POWERED_BY_PATTERNS",
    "FRAMEWORK_VERSION_HEADERS",
    "KNOWN_VULNERABLE_VERSIONS",
    "DEBUG_INDICATORS",
    "DEPENDENCY_FILES",
    "CVE_PATTERNS",
]

# Server header patterns that reveal exact versions
SERVER_VERSION_PATTERNS: list[tuple[str, str, str]] = [
    (r"(?i)^Apache/(\d+\.\d+[\.\d]*)", "Apache", "Web server version disclosure"),
    (r"(?i)^nginx/(\d+\.\d+[\.\d]*)", "Nginx", "Web server version disclosure"),
    (r"(?i)^Microsoft-IIS/(\d+\.\d+)", "Microsoft-IIS", "Web server version disclosure"),
    (r"(?i)^lighttpd/(\d+\.\d+[\.\d]*)", "Lighttpd", "Web server version disclosure"),
    (r"(?i)^Caddy/(\d+\.\d+[\.\d]*)", "Caddy", "Web server version disclosure"),
    (r"(?i)^Tomcat[/-](\d+\.\d+[\.\d]*)", "Apache Tomcat", "Application server version disclosure"),
    (r"(?i)^Jetty[/-](\d+\.\d+[\.\d]*)", "Jetty", "Application server version disclosure"),
    (r"(?i)^gunicorn/(\d+\.\d+[\.\d]*)", "Gunicorn", "Application server version disclosure"),
    (r"(?i)^uvicorn/(\d+\.\d+[\.\d]*)", "Uvicorn", "Application server version disclosure"),
    (r"(?i)^OpenResty/(\d+\.\d+[\.\d]*)", "OpenResty", "Web server version disclosure"),
    (r"(?i)^cloudflare", "Cloudflare", "CDN/WAF disclosure"),
    (r"(?i)^akamai", "Akamai", "CDN/WAF disclosure"),
]

# X-Powered-By and technology version patterns
POWERED_BY_PATTERNS: list[tuple[str, str, str]] = [
    (r"(?i)PHP/(\d+\.\d+[\.\d]*)", "PHP", "Backend language version disclosure"),
    (r"(?i)Express", "Express", "Node.js framework disclosure"),
    (r"(?i)ASP\.NET", "ASP.NET", "Microsoft framework disclosure"),
    (r"(?i)Next\.?JS", "Next.js", "React framework disclosure"),
    (r"(?i)Nuxt", "Nuxt", "Vue.js framework disclosure"),
    (r"(?i)Fastify", "Fastify", "Node.js framework disclosure"),
    (r"(?i)Koa", "Koa", "Node.js framework disclosure"),
    (r"(?i)Hapi", "Hapi", "Node.js framework disclosure"),
    (r"(?i)Spring", "Spring Framework", "Java framework disclosure"),
    (r"(?i)Rack/(\d+\.\d+[\.\d]*)", "Rack", "Ruby middleware disclosure"),
    (r"(?i)Phusion Passenger", "Phusion Passenger", "Ruby application server disclosure"),
    (r"(?i)Puma", "Puma", "Ruby application server disclosure"),
    (r"(?i)Unicorn", "Unicorn", "Ruby application server disclosure"),
    (r"(?i)Gunicorn", "Gunicorn", "Python application server disclosure"),
    (r"(?i)Django/(\d+\.\d+[\.\d]*)", "Django", "Python framework disclosure"),
    (r"(?i)Flask", "Flask", "Python framework disclosure"),
    (r"(?i)FastAPI", "FastAPI", "Python framework disclosure"),
    (r"(?i)Laravel", "Laravel", "PHP framework disclosure"),
    (r"(?i)Symfony", "Symfony", "PHP framework disclosure"),
    (r"(?i)CodeIgniter", "CodeIgniter", "PHP framework disclosure"),
    (r"(?i)WordPress/(\d+\.\d+[\.\d]*)", "WordPress", "CMS version disclosure"),
    (r"(?i)Drupal", "Drupal", "CMS version disclosure"),
    (r"(?i)Joomla", "Joomla", "CMS version disclosure"),
]

# Framework-specific version headers
FRAMEWORK_VERSION_HEADERS: dict[str, tuple[str, str]] = {
    "x-aspnet-version": ("ASP.NET", "Microsoft framework version disclosure"),
    "x-aspnetmvc-version": ("ASP.NET MVC", "Microsoft MVC framework version disclosure"),
    "x-aspnetmvc": ("ASP.NET MVC", "Microsoft MVC framework disclosure"),
    "x-runtime": ("Ruby on Rails", "Ruby/Rails runtime disclosure"),
    "x-rack-version": ("Rack", "Ruby middleware version disclosure"),
    "x-powered-by-plesk": ("Plesk", "Hosting control panel disclosure"),
    "x-generator": ("CMS/Generator", "Content management system disclosure"),
    "x-drupal-cache": ("Drupal", "Drupal CMS disclosure"),
    "x-litespeed-cache": ("LiteSpeed", "LiteSpeed cache disclosure"),
    "x-w3-total-cache": ("W3 Total Cache", "WordPress plugin disclosure"),
    "x-mod-pagespeed": ("mod_pagespeed", "Apache module version disclosure"),
    "x-varnish": ("Varnish", "Reverse proxy disclosure"),
    "x-fastly-cache": ("Fastly", "CDN cache disclosure"),
    "x-sucuri-id": ("Sucuri", "WAF/CDN disclosure"),
    "x-content-powered-by": ("CMS", "Content platform disclosure"),
    "x-b3-traceid": ("Zipkin/Brave", "Distributed tracing header disclosure"),
    "x-request-id": ("Request ID", "Request tracing disclosure"),
    "x-correlation-id": ("Correlation ID", "Request correlation disclosure"),
    "x-envoy-upstream-service-time": ("Envoy", "Service mesh disclosure"),
    "x-serve-by": ("Infrastructure", "Infrastructure disclosure"),
    "x-powered-by": ("X-Powered-By", "Technology stack disclosure"),
}

# Known vulnerable framework version patterns
KNOWN_VULNERABLE_VERSIONS: list[tuple[str, str, str, str]] = [
    (r"Apache/2\.2\.\d+", "Apache 2.2.x", "high", "End-of-life Apache version with known CVEs"),
    (
        r"Apache/2\.4\.(?:[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-6])\b",
        "Apache 2.4.x < 2.4.47",
        "medium",
        "Apache version potentially vulnerable to CVE-2021-33193 and earlier",
    ),
    (r"nginx/1\.[0-9]\.", "Nginx 1.x < 1.10", "high", "End-of-life Nginx version"),
    (
        r"nginx/1\.1[0-5]\.",
        "Nginx 1.1x < 1.16",
        "medium",
        "Nginx version with known vulnerabilities",
    ),
    (
        r"nginx/1\.16\.[0-5]\b",
        "Nginx 1.16.x < 1.16.6",
        "medium",
        "Nginx version with known vulnerabilities",
    ),
    (r"Microsoft-IIS/6\.0", "IIS 6.0", "critical", "End-of-life IIS with critical vulnerabilities"),
    (r"Microsoft-IIS/7\.0", "IIS 7.0", "high", "End-of-life IIS version"),
    (r"Microsoft-IIS/7\.5", "IIS 7.5", "high", "End-of-life IIS version"),
    (r"Microsoft-IIS/8\.0", "IIS 8.0", "medium", "Outdated IIS version"),
    (r"Tomcat/8\.", "Tomcat 8.x", "medium", "Outdated Tomcat version"),
    (r"Tomcat/7\.", "Tomcat 7.x", "high", "End-of-life Tomcat version"),
    (r"Tomcat/6\.", "Tomcat 6.x", "critical", "End-of-life Tomcat version"),
    (r"PHP/5\.[0-4]\.", "PHP 5.0-5.4", "critical", "End-of-life PHP with critical vulnerabilities"),
    (r"PHP/5\.5\.", "PHP 5.5", "high", "End-of-life PHP version"),
    (r"PHP/5\.6\.", "PHP 5.6", "medium", "End-of-life PHP version"),
    (r"PHP/7\.[0-3]\.", "PHP 7.0-7.3", "medium", "Outdated PHP version"),
    (r"OpenSSL/1\.0\.", "OpenSSL 1.0.x", "high", "End-of-life OpenSSL with known CVEs"),
    (r"OpenSSL/1\.1\.[0-5]\b", "OpenSSL 1.1.0-1.1.5", "medium", "Outdated OpenSSL version"),
    (r"Django/1\.", "Django 1.x", "critical", "End-of-life Django with critical vulnerabilities"),
    (r"Django/2\.[01]\.", "Django 2.0-2.1", "high", "End-of-life Django version"),
    (r"Django/2\.2\.", "Django 2.2", "medium", "Django 2.2 approaching end of life"),
    (r"Django/3\.[01]\.", "Django 3.0-3.1", "medium", "Outdated Django version"),
    (r"Rails/3\.", "Rails 3.x", "critical", "End-of-life Rails with critical vulnerabilities"),
    (r"Rails/4\.", "Rails 4.x", "high", "End-of-life Rails version"),
    (r"Rails/5\.[01]\.", "Rails 5.0-5.1", "medium", "Outdated Rails version"),
    (
        r"Laravel/5\.[0-4]\.",
        "Laravel 5.0-5.4",
        "high",
        "Outdated Laravel with known vulnerabilities",
    ),
    (
        r"WordPress/5\.[0-5]\.",
        "WordPress 5.0-5.5",
        "medium",
        "Outdated WordPress with known vulnerabilities",
    ),
    (r"WordPress/4\.", "WordPress 4.x", "high", "End-of-life WordPress version"),
    (
        r"WordPress/3\.",
        "WordPress 3.x",
        "critical",
        "End-of-life WordPress with critical vulnerabilities",
    ),
    (r"jQuery\s+1\.", "jQuery 1.x", "medium", "Outdated jQuery with known XSS vulnerabilities"),
    (r"jQuery\s+2\.[01]\.", "jQuery 2.0-2.1", "medium", "Outdated jQuery version"),
    (r"jQuery\s+3\.[0-3]\.", "jQuery 3.0-3.3", "low", "Outdated jQuery version"),
]

# Debug and development mode indicators
DEBUG_INDICATORS: list[tuple[str, str, str]] = [
    (r"(?i)debug\s*[:=]\s*true", "Debug mode enabled", "high"),
    (r"(?i)debug[_\s]mode\s*[:=]\s*true", "Debug mode enabled", "high"),
    (r"(?i)development\s*mode", "Development mode detected", "medium"),
    (r"(?i)stack\s*trace", "Stack trace exposure", "high"),
    (r"(?i)traceback\s*\(", "Python traceback exposure", "high"),
    (r"(?i)at\s+\w+\.\w+\([^)]*:\d+\)", "Java/.NET stack frame detected", "medium"),
    (r"(?i)exception\s*:\s*", "Exception details exposed", "high"),
    (r"(?i)error\s*details", "Error details exposed", "medium"),
    (r"(?i)internal\s*server\s*error.*\n", "Internal server error details", "medium"),
    (r"(?i)file\s*not\s*found.*\n", "File path disclosure", "medium"),
    (r"(?i)SQL\s*(syntax|error|exception)", "SQL error exposure", "critical"),
    (r"(?i)Warning\s*:\s*", "PHP warning exposure", "medium"),
    (r"(?i)Notice\s*:\s*", "PHP notice exposure", "low"),
    (r"(?i)Deprecated\s*:\s*", "PHP deprecation notice", "low"),
    (r"(?i)Fatal\s*error\s*:", "Fatal error exposure", "high"),
    (r"(?i)parse\s*error\s*:", "Parse error exposure", "high"),
    (r"(?i)uncaught\s*(exception|error)", "Uncaught exception exposure", "high"),
    (r"(?i)throwable", "Throwable stack trace", "high"),
    (r"(?i)whoops!", "Whoops error page (Laravel)", "high"),
    (r"(?i)flask\s*debugger", "Flask debugger exposed", "critical"),
    (r"(?i)django\s*debug", "Django debug page", "high"),
    (r"(?i)rails\s*error", "Rails error page", "medium"),
    (r"(?i)spring\s*boot\s*.*\s*error", "Spring Boot error page", "medium"),
    (r"(?i)whitelabel\s*error", "Spring Boot Whitelabel Error", "medium"),
    (r"(?i)webpack\s*dev\s*server", "Webpack dev server exposed", "medium"),
    (r"(?i)hot\s*module\s*replacement", "HMR enabled", "medium"),
    (r"(?i)react\s*devtools", "React DevTools detected", "low"),
    (r"(?i)vue\s*devtools", "Vue DevTools detected", "low"),
    (r"(?i)__NEXT_DATA__", "Next.js data exposure", "low"),
]

# Dependency disclosure file patterns
DEPENDENCY_FILES: list[tuple[str, str, str]] = [
    ("/package.json", "package.json", "Node.js dependency disclosure"),
    ("/composer.json", "composer.json", "PHP dependency disclosure"),
    ("/composer.lock", "composer.lock", "PHP locked dependency disclosure"),
    ("/pom.xml", "pom.xml", "Java/Maven dependency disclosure"),
    ("/Gemfile.lock", "Gemfile.lock", "Ruby dependency disclosure"),
    ("/requirements.txt", "requirements.txt", "Python dependency disclosure"),
    ("/go.mod", "go.mod", "Go dependency disclosure"),
    ("/go.sum", "go.sum", "Go dependency checksum disclosure"),
    ("/yarn.lock", "yarn.lock", "Yarn dependency disclosure"),
    ("/package-lock.json", "package-lock.json", "NPM dependency disclosure"),
    ("/Cargo.toml", "Cargo.toml", "Rust dependency disclosure"),
    ("/Cargo.lock", "Cargo.lock", "Rust locked dependency disclosure"),
    ("/Pipfile.lock", "Pipfile.lock", "Python Pipfile disclosure"),
    ("/poetry.lock", "poetry.lock", "Python Poetry dependency disclosure"),
    ("/mix.lock", "mix.lock", "Elixir dependency disclosure"),
    ("/pubspec.lock", "pubspec.lock", "Dart/Flutter dependency disclosure"),
]

# Known CVE pattern signatures in responses
CVE_PATTERNS: list[tuple[str, str, str, str]] = [
    (r"(?i)CVE-\d{4}-\d{4,}", "CVE reference exposed", "medium", "CVE reference found in response"),
    (r"(?i)XSS(?:ed|ing|able)?", "XSS indicator", "medium", "Potential XSS reference in response"),
    (
        r"(?i)SQL\s*injection",
        "SQL injection reference",
        "high",
        "SQL injection reference in response",
    ),
    (
        r"(?i)path\s*traversal",
        "Path traversal reference",
        "high",
        "Path traversal reference in response",
    ),
    (
        r"(?i)command\s*injection",
        "Command injection reference",
        "high",
        "Command injection reference in response",
    ),
    (
        r"(?i)directory\s*listing",
        "Directory listing enabled",
        "medium",
        "Directory listing exposed in response",
    ),
    (r"(?i)index\s*of\s*/", "Directory index exposed", "medium", "Directory index listing exposed"),
    (
        r"(?i)powered\s*by\s*(?:cPanel|Plesk|Webmin|Virtualmin)",
        "Control panel disclosure",
        "medium",
        "Hosting control panel identified",
    ),
    (
        r"(?i)admin\s*(?:panel|dashboard|console)",
        "Admin interface reference",
        "medium",
        "Admin interface reference found",
    ),
    (r"(?i)phpMyAdmin", "phpMyAdmin disclosure", "high", "phpMyAdmin interface detected"),
    (r"(?i)adminer", "Adminer disclosure", "high", "Adminer database tool detected"),
    (
        r"(?i)swagger\s*(?:ui|json|yaml)",
        "Swagger/OpenAPI exposed",
        "medium",
        "API documentation publicly accessible",
    ),
    (
        r"(?i)graphql\s*(?:playground|ide|console)",
        "GraphQL IDE exposed",
        "medium",
        "GraphQL development interface accessible",
    ),
    (r"(?i)/actuator", "Spring Boot Actuator", "high", "Spring Boot management endpoints exposed"),
    (r"(?i)/console", "Admin console reference", "medium", "Console interface reference found"),
    (r"(?i)/manager/html", "Tomcat Manager", "high", "Tomcat Manager interface accessible"),
    (r"(?i)/solr/", "Apache Solr", "medium", "Apache Solr interface accessible"),
    (r"(?i)/jenkins/", "Jenkins", "high", "Jenkins CI interface accessible"),
    (r"(?i)/wp-admin", "WordPress admin", "medium", "WordPress admin interface accessible"),
    (r"(?i)/wp-login", "WordPress login", "low", "WordPress login page accessible"),
    (r"(?i)/xmlrpc\.php", "XML-RPC endpoint", "medium", "WordPress XML-RPC endpoint accessible"),
    (r"(?i)/wp-json", "WordPress REST API", "low", "WordPress REST API accessible"),
]
