apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cyber-pipeline.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cyber-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  app-secret-key: {{ .Values.config.appSecretKey | b64enc | quote }}
