"""Constants and configuration for race condition probing."""

__all__ = [
    "RACE_PRONE_PATH_KEYWORDS",
    "RACE_PRONE_PARAM_NAMES",
    "RACE_BODY_KEYWORDS",
    "AUTH_RACE_PATH_KEYWORDS",
    "STATE_TRANSITION_KEYWORDS",
    "RESOURCE_ALLOCATION_KEYWORDS",
    "RACE_CONCURRENCY_LEVELS",
    "RC_CONFIDENCE",
    "RC_SEVERITY",
    "RACE_PROBE_SPEC",
]

RACE_PRONE_PATH_KEYWORDS = frozenset(
    {
        "payment",
        "pay",
        "charge",
        "bill",
        "invoice",
        "checkout",
        "purchase",
        "coupon",
        "discount",
        "promo",
        "voucher",
        "redeem",
        "transfer",
        "withdraw",
        "deposit",
        "fund",
        "register",
        "signup",
        "enroll",
        "subscribe",
        "vote",
        "claim",
        "apply",
        "book",
        "booking",
        "reserve",
        "reservation",
        "order",
        "cart",
        "buy",
        "sell",
        "trade",
        "balance",
        "wallet",
        "credit",
        "debit",
        "stock",
        "inventory",
        "quantity",
        "seat",
        "ticket",
    }
)

RACE_PRONE_PARAM_NAMES = frozenset(
    {
        "coupon",
        "coupon_code",
        "promo",
        "promo_code",
        "discount",
        "voucher",
        "voucher_code",
        "redeem_code",
        "amount",
        "quantity",
        "qty",
        "count",
        "units",
        "transfer_to",
        "transfer_from",
        "destination",
        "source",
        "from_account",
        "to_account",
        "recipient",
        "vote_id",
        "candidate",
        "choice",
        "option",
        "claim_id",
        "claim_type",
        "seat_id",
        "seat_number",
        "ticket_id",
        "stock_id",
        "product_id",
    }
)

RACE_CONCURRENCY_LEVELS = [5, 10, 20]

RACE_BODY_KEYWORDS = frozenset(
    {
        "coupon",
        "discount",
        "promo",
        "voucher",
        "redeem",
        "balance",
        "amount",
        "credit",
        "debit",
        "transfer",
        "payment",
        "charge",
        "invoice",
        "checkout",
        "quantity",
        "stock",
        "inventory",
        "seat",
        "ticket",
        "vote",
        "claim",
        "order",
        "cart",
        "success",
        "applied",
        "processed",
        "completed",
        "duplicate",
        "already",
        "used",
        "expired",
        "invalid",
        "insufficient",
        "exceeded",
        "limit",
    }
)

AUTH_RACE_PATH_KEYWORDS = frozenset(
    {
        "login",
        "signin",
        "authenticate",
        "auth",
        "token",
        "register",
        "signup",
        "enroll",
        "verify",
        "confirm",
        "reset",
        "recover",
        "activate",
        "deactivate",
        "session",
        "logout",
        "signout",
    }
)

STATE_TRANSITION_KEYWORDS = frozenset(
    {
        "status",
        "state",
        "phase",
        "step",
        "stage",
        "approve",
        "reject",
        "confirm",
        "cancel",
        "enable",
        "disable",
        "lock",
        "unlock",
        "pause",
        "resume",
        "start",
        "stop",
        "publish",
        "unpublish",
        "archive",
        "restore",
    }
)

RESOURCE_ALLOCATION_KEYWORDS = frozenset(
    {
        "allocate",
        "assign",
        "reserve",
        "book",
        "hold",
        "seat",
        "room",
        "slot",
        "ticket",
        "license",
        "quota",
        "limit",
        "capacity",
        "available",
    }
)

RC_CONFIDENCE = {
    "inconsistent_responses": 0.85,
    "duplicate_processing": 0.90,
    "toctou_vulnerability": 0.82,
    "auth_race_condition": 0.78,
    "state_transition_race": 0.80,
    "resource_allocation_race": 0.75,
    "missing_idempotency": 0.65,
    "timing_discrepancy": 0.70,
    "balance_inconsistency": 0.88,
}

RC_SEVERITY = {
    "inconsistent_responses": "high",
    "duplicate_processing": "critical",
    "toctou_vulnerability": "high",
    "auth_race_condition": "high",
    "state_transition_race": "medium",
    "resource_allocation_race": "medium",
    "missing_idempotency": "low",
    "timing_discrepancy": "low",
    "balance_inconsistency": "critical",
}

RACE_PROBE_SPEC = {
    "key": "race_condition_probe",
    "label": "Race Condition Probe",
    "description": "Actively test stateful endpoints for race condition vulnerabilities by sending concurrent requests.",
    "group": "active",
    "input_kind": "priority_urls_and_cache",
}
