"""Tenant isolation constants for multi-tenant SaaS security testing."""

import re

TENANT_PARAM_NAMES = {
    "tenant_id",
    "tenantid",
    "tenant",
    "org_id",
    "orgid",
    "org",
    "organization_id",
    "organizationid",
    "organization",
    "account_id",
    "accountid",
    "account",
    "company_id",
    "companyid",
    "company",
    "site_id",
    "siteid",
    "site",
    "group_id",
    "groupid",
    "group",
    "workspace_id",
    "workspaceid",
    "workspace",
    "project_id",
    "projectid",
    "project",
    "team_id",
    "teamid",
    "team",
    "customer_id",
    "customerid",
    "customer",
    "client_id",
    "clientid",
    "client",
    "domain_id",
    "domainid",
    "domain",
    "namespace",
    "namespace_id",
    "environment_id",
    "environmentid",
    "environment",
    "instance_id",
    "instanceid",
    "instance",
    "app_id",
    "appid",
    "app",
    "subdomain",
    "x_tenant_id",
    "x_org_id",
    "x_account_id",
}

TENANT_HEADER_NAMES = {
    "x-tenant-id",
    "x-organization-id",
    "x-org-id",
    "x-account-id",
    "x-company-id",
    "x-site-id",
    "x-workspace-id",
    "x-project-id",
    "x-team-id",
    "x-customer-id",
    "x-client-id",
    "x-namespace",
    "x-environment-id",
    "x-instance-id",
    "x-app-id",
    "x-subdomain",
    "x-multi-tenant-id",
    "x-tenant",
    "x-org",
    "x-company",
}

TENANT_PATH_PATTERN = re.compile(
    r"/(?:tenant|org|organization|account|company|site|workspace|project|team|customer|client|namespace|environment|instance|app)s?/([a-zA-Z0-9_-]+)",
    re.IGNORECASE,
)

MULTI_TENANT_INDICATORS = {
    "multi-tenant",
    "multitenant",
    "multi_tenant",
    "tenant",
    "organization",
    "workspace",
    "saas",
    "x-tenant-id",
    "x-org-id",
    "x-account-id",
    "tenant_id",
    "org_id",
    "account_id",
    "company_id",
    "workspace_id",
}

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) SecurityPipeline/1.0"
